//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPNDBInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_LesionStatusAll
    {
        public int RecordID { get; set; }
        public string LesionStatus { get; set; }
        public string LesionCommentFlag { get; set; }
        public string MIRAOverlayRequired { get; set; }
        public int ForTarget { get; set; }
        public int ForBL { get; set; }
        public int InitialCLD { get; set; }
        public int ForNonTarget { get; set; }
        public int ForFU { get; set; }
    }
}
