//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPNDBInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_ModalityNumbers
    {
        public int ModalityNumber { get; set; }
    }
}
