//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPNDBInput
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PSH_IPN_8_55_58102_003_DEVEntities : DbContext
    {
        public PSH_IPN_8_55_58102_003_DEVEntities()
            : base("name=PSH_IPN_8_55_58102_003_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LU_Anatomy> LU_Anatomy { get; set; }
        public virtual DbSet<LU_BestOverallResponse> LU_BestOverallResponse { get; set; }
        public virtual DbSet<LU_BoneScanAssessment> LU_BoneScanAssessment { get; set; }
        public virtual DbSet<LU_BoneScanLesionLocation> LU_BoneScanLesionLocation { get; set; }
        public virtual DbSet<LU_BoneScanLesionStatus> LU_BoneScanLesionStatus { get; set; }
        public virtual DbSet<LU_BoneScanQualityComment> LU_BoneScanQualityComment { get; set; }
        public virtual DbSet<LU_FinalVisitResponse> LU_FinalVisitResponse { get; set; }
        public virtual DbSet<LU_LesionLabel> LU_LesionLabel { get; set; }
        public virtual DbSet<LU_LesionResponse_NonTarget> LU_LesionResponse_NonTarget { get; set; }
        public virtual DbSet<LU_LesionSiteOrgan> LU_LesionSiteOrgan { get; set; }
        public virtual DbSet<LU_LesionStatusAll> LU_LesionStatusAll { get; set; }
        public virtual DbSet<LU_LesionTypeAll> LU_LesionTypeAll { get; set; }
        public virtual DbSet<LU_Modality> LU_Modality { get; set; }
        public virtual DbSet<LU_QualityComment> LU_QualityComment { get; set; }
        public virtual DbSet<LU_RadiologyQuality> LU_RadiologyQuality { get; set; }
        public virtual DbSet<LU_ReviewerVisitResponse> LU_ReviewerVisitResponse { get; set; }
        public virtual DbSet<LU_ModalityNumbers> LU_ModalityNumbers { get; set; }
    }
}
