#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMover
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PSH_BOR1_003_1200_131_DEV")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCD_AE(CD_AE instance);
    partial void UpdateCD_AE(CD_AE instance);
    partial void DeleteCD_AE(CD_AE instance);
    partial void InsertCD_BPSY(CD_BPSY instance);
    partial void UpdateCD_BPSY(CD_BPSY instance);
    partial void DeleteCD_BPSY(CD_BPSY instance);
    partial void InsertCD_NDI(CD_NDI instance);
    partial void UpdateCD_NDI(CD_NDI instance);
    partial void DeleteCD_NDI(CD_NDI instance);
    partial void InsertCD_PE(CD_PE instance);
    partial void UpdateCD_PE(CD_PE instance);
    partial void DeleteCD_PE(CD_PE instance);
    partial void InsertCD_ROR(CD_ROR instance);
    partial void UpdateCD_ROR(CD_ROR instance);
    partial void DeleteCD_ROR(CD_ROR instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DataMover.Properties.Settings.Default.PSH_BOR1_003_1200_131_DEVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CD_AE> CD_AEs
		{
			get
			{
				return this.GetTable<CD_AE>();
			}
		}
		
		public System.Data.Linq.Table<CD_BPSY> CD_BPSies
		{
			get
			{
				return this.GetTable<CD_BPSY>();
			}
		}
		
		public System.Data.Linq.Table<CD_NDI> CD_NDIs
		{
			get
			{
				return this.GetTable<CD_NDI>();
			}
		}
		
		public System.Data.Linq.Table<CD_PE> CD_PEs
		{
			get
			{
				return this.GetTable<CD_PE>();
			}
		}
		
		public System.Data.Linq.Table<CD_ROR> CD_RORs
		{
			get
			{
				return this.GetTable<CD_ROR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CD_AE")]
	public partial class CD_AE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RECORDID;
		
		private bool _ISVALID;
		
		private string _STUDY;
		
		private string _CENTRE;
		
		private string _PT;
		
		private string _AEMNM;
		
		private string _AEONDT;
		
		private string _AEENDDT;
		
		private string _AEOUT;
		
		private string _AETHPA;
		
		private string _CTCAE;
		
		private string _AEACTE;
		
		private string _AERDTOX;
		
		private string _AESERA;
		
		private string _AESDTH;
		
		private string _AESLIFE;
		
		private string _AESDISAB;
		
		private string _AESRHOS;
		
		private string _AESPHOS;
		
		private string _AESCONG;
		
		private string _AESMIE;
		
		private string _AESPI;
		
		private string _AEREL;
		
		private string _AEFUP;
		
		private string _AEX1;
		
		private string _VISOUT;
		
		private string _TINV;
		
		private string _GPVIS;
		
		private string _REFERS;
		
		private string _PHYSIO;
		
		private string _OCCTHP;
		
		private string _NURSE;
		
		private string _OTH1;
		
		private string _AEX2;
		
		private string _VISITS1;
		
		private string _VISITS2;
		
		private string _VISITS3;
		
		private string _VISITS4;
		
		private string _VISITS5;
		
		private string _VISITS6;
		
		private string _VISITS7;
		
		private string _EXPRNC;
		
		private string _MRISC;
		
		private string _CTSCAN;
		
		private string _US;
		
		private string _XRAYB;
		
		private string _OTH2;
		
		private string _AEX3;
		
		private string _ADMISDT1;
		
		private string _DISCHDT1;
		
		private string _ICUDYS1;
		
		private string _EMERG1;
		
		private string _ADMISDT2;
		
		private string _DISCHDT2;
		
		private string _ICUDYS2;
		
		private string _EMERG2;
		
		private string _ADMISDT3;
		
		private string _DISCHDT3;
		
		private string _ICUDYS3;
		
		private string _EMERG3;
		
		private string _AEX4;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRECORDIDChanging(int value);
    partial void OnRECORDIDChanged();
    partial void OnISVALIDChanging(bool value);
    partial void OnISVALIDChanged();
    partial void OnSTUDYChanging(string value);
    partial void OnSTUDYChanged();
    partial void OnCENTREChanging(string value);
    partial void OnCENTREChanged();
    partial void OnPTChanging(string value);
    partial void OnPTChanged();
    partial void OnAEMNMChanging(string value);
    partial void OnAEMNMChanged();
    partial void OnAEONDTChanging(string value);
    partial void OnAEONDTChanged();
    partial void OnAEENDDTChanging(string value);
    partial void OnAEENDDTChanged();
    partial void OnAEOUTChanging(string value);
    partial void OnAEOUTChanged();
    partial void OnAETHPAChanging(string value);
    partial void OnAETHPAChanged();
    partial void OnCTCAEChanging(string value);
    partial void OnCTCAEChanged();
    partial void OnAEACTEChanging(string value);
    partial void OnAEACTEChanged();
    partial void OnAERDTOXChanging(string value);
    partial void OnAERDTOXChanged();
    partial void OnAESERAChanging(string value);
    partial void OnAESERAChanged();
    partial void OnAESDTHChanging(string value);
    partial void OnAESDTHChanged();
    partial void OnAESLIFEChanging(string value);
    partial void OnAESLIFEChanged();
    partial void OnAESDISABChanging(string value);
    partial void OnAESDISABChanged();
    partial void OnAESRHOSChanging(string value);
    partial void OnAESRHOSChanged();
    partial void OnAESPHOSChanging(string value);
    partial void OnAESPHOSChanged();
    partial void OnAESCONGChanging(string value);
    partial void OnAESCONGChanged();
    partial void OnAESMIEChanging(string value);
    partial void OnAESMIEChanged();
    partial void OnAESPIChanging(string value);
    partial void OnAESPIChanged();
    partial void OnAERELChanging(string value);
    partial void OnAERELChanged();
    partial void OnAEFUPChanging(string value);
    partial void OnAEFUPChanged();
    partial void OnAEX1Changing(string value);
    partial void OnAEX1Changed();
    partial void OnVISOUTChanging(string value);
    partial void OnVISOUTChanged();
    partial void OnTINVChanging(string value);
    partial void OnTINVChanged();
    partial void OnGPVISChanging(string value);
    partial void OnGPVISChanged();
    partial void OnREFERSChanging(string value);
    partial void OnREFERSChanged();
    partial void OnPHYSIOChanging(string value);
    partial void OnPHYSIOChanged();
    partial void OnOCCTHPChanging(string value);
    partial void OnOCCTHPChanged();
    partial void OnNURSEChanging(string value);
    partial void OnNURSEChanged();
    partial void OnOTH1Changing(string value);
    partial void OnOTH1Changed();
    partial void OnAEX2Changing(string value);
    partial void OnAEX2Changed();
    partial void OnVISITS1Changing(string value);
    partial void OnVISITS1Changed();
    partial void OnVISITS2Changing(string value);
    partial void OnVISITS2Changed();
    partial void OnVISITS3Changing(string value);
    partial void OnVISITS3Changed();
    partial void OnVISITS4Changing(string value);
    partial void OnVISITS4Changed();
    partial void OnVISITS5Changing(string value);
    partial void OnVISITS5Changed();
    partial void OnVISITS6Changing(string value);
    partial void OnVISITS6Changed();
    partial void OnVISITS7Changing(string value);
    partial void OnVISITS7Changed();
    partial void OnEXPRNCChanging(string value);
    partial void OnEXPRNCChanged();
    partial void OnMRISCChanging(string value);
    partial void OnMRISCChanged();
    partial void OnCTSCANChanging(string value);
    partial void OnCTSCANChanged();
    partial void OnUSChanging(string value);
    partial void OnUSChanged();
    partial void OnXRAYBChanging(string value);
    partial void OnXRAYBChanged();
    partial void OnOTH2Changing(string value);
    partial void OnOTH2Changed();
    partial void OnAEX3Changing(string value);
    partial void OnAEX3Changed();
    partial void OnADMISDT1Changing(string value);
    partial void OnADMISDT1Changed();
    partial void OnDISCHDT1Changing(string value);
    partial void OnDISCHDT1Changed();
    partial void OnICUDYS1Changing(string value);
    partial void OnICUDYS1Changed();
    partial void OnEMERG1Changing(string value);
    partial void OnEMERG1Changed();
    partial void OnADMISDT2Changing(string value);
    partial void OnADMISDT2Changed();
    partial void OnDISCHDT2Changing(string value);
    partial void OnDISCHDT2Changed();
    partial void OnICUDYS2Changing(string value);
    partial void OnICUDYS2Changed();
    partial void OnEMERG2Changing(string value);
    partial void OnEMERG2Changed();
    partial void OnADMISDT3Changing(string value);
    partial void OnADMISDT3Changed();
    partial void OnDISCHDT3Changing(string value);
    partial void OnDISCHDT3Changed();
    partial void OnICUDYS3Changing(string value);
    partial void OnICUDYS3Changed();
    partial void OnEMERG3Changing(string value);
    partial void OnEMERG3Changed();
    partial void OnAEX4Changing(string value);
    partial void OnAEX4Changed();
    #endregion
		
		public CD_AE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RECORDID
		{
			get
			{
				return this._RECORDID;
			}
			set
			{
				if ((this._RECORDID != value))
				{
					this.OnRECORDIDChanging(value);
					this.SendPropertyChanging();
					this._RECORDID = value;
					this.SendPropertyChanged("RECORDID");
					this.OnRECORDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISVALID", DbType="Bit NOT NULL")]
		public bool ISVALID
		{
			get
			{
				return this._ISVALID;
			}
			set
			{
				if ((this._ISVALID != value))
				{
					this.OnISVALIDChanging(value);
					this.SendPropertyChanging();
					this._ISVALID = value;
					this.SendPropertyChanged("ISVALID");
					this.OnISVALIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY", DbType="Char(9)")]
		public string STUDY
		{
			get
			{
				return this._STUDY;
			}
			set
			{
				if ((this._STUDY != value))
				{
					this.OnSTUDYChanging(value);
					this.SendPropertyChanging();
					this._STUDY = value;
					this.SendPropertyChanged("STUDY");
					this.OnSTUDYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRE", DbType="Char(5)")]
		public string CENTRE
		{
			get
			{
				return this._CENTRE;
			}
			set
			{
				if ((this._CENTRE != value))
				{
					this.OnCENTREChanging(value);
					this.SendPropertyChanging();
					this._CENTRE = value;
					this.SendPropertyChanged("CENTRE");
					this.OnCENTREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT", DbType="Char(10)")]
		public string PT
		{
			get
			{
				return this._PT;
			}
			set
			{
				if ((this._PT != value))
				{
					this.OnPTChanging(value);
					this.SendPropertyChanging();
					this._PT = value;
					this.SendPropertyChanged("PT");
					this.OnPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEMNM", DbType="Char(50)")]
		public string AEMNM
		{
			get
			{
				return this._AEMNM;
			}
			set
			{
				if ((this._AEMNM != value))
				{
					this.OnAEMNMChanging(value);
					this.SendPropertyChanging();
					this._AEMNM = value;
					this.SendPropertyChanged("AEMNM");
					this.OnAEMNMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEONDT", DbType="Char(9)")]
		public string AEONDT
		{
			get
			{
				return this._AEONDT;
			}
			set
			{
				if ((this._AEONDT != value))
				{
					this.OnAEONDTChanging(value);
					this.SendPropertyChanging();
					this._AEONDT = value;
					this.SendPropertyChanged("AEONDT");
					this.OnAEONDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEENDDT", DbType="Char(9)")]
		public string AEENDDT
		{
			get
			{
				return this._AEENDDT;
			}
			set
			{
				if ((this._AEENDDT != value))
				{
					this.OnAEENDDTChanging(value);
					this.SendPropertyChanging();
					this._AEENDDT = value;
					this.SendPropertyChanged("AEENDDT");
					this.OnAEENDDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEOUT", DbType="Char(20)")]
		public string AEOUT
		{
			get
			{
				return this._AEOUT;
			}
			set
			{
				if ((this._AEOUT != value))
				{
					this.OnAEOUTChanging(value);
					this.SendPropertyChanging();
					this._AEOUT = value;
					this.SendPropertyChanged("AEOUT");
					this.OnAEOUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AETHPA", DbType="Char(20)")]
		public string AETHPA
		{
			get
			{
				return this._AETHPA;
			}
			set
			{
				if ((this._AETHPA != value))
				{
					this.OnAETHPAChanging(value);
					this.SendPropertyChanging();
					this._AETHPA = value;
					this.SendPropertyChanged("AETHPA");
					this.OnAETHPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTCAE", DbType="Char(20)")]
		public string CTCAE
		{
			get
			{
				return this._CTCAE;
			}
			set
			{
				if ((this._CTCAE != value))
				{
					this.OnCTCAEChanging(value);
					this.SendPropertyChanging();
					this._CTCAE = value;
					this.SendPropertyChanged("CTCAE");
					this.OnCTCAEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEACTE", DbType="Char(20)")]
		public string AEACTE
		{
			get
			{
				return this._AEACTE;
			}
			set
			{
				if ((this._AEACTE != value))
				{
					this.OnAEACTEChanging(value);
					this.SendPropertyChanging();
					this._AEACTE = value;
					this.SendPropertyChanged("AEACTE");
					this.OnAEACTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AERDTOX", DbType="Char(20)")]
		public string AERDTOX
		{
			get
			{
				return this._AERDTOX;
			}
			set
			{
				if ((this._AERDTOX != value))
				{
					this.OnAERDTOXChanging(value);
					this.SendPropertyChanging();
					this._AERDTOX = value;
					this.SendPropertyChanged("AERDTOX");
					this.OnAERDTOXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESERA", DbType="Char(20)")]
		public string AESERA
		{
			get
			{
				return this._AESERA;
			}
			set
			{
				if ((this._AESERA != value))
				{
					this.OnAESERAChanging(value);
					this.SendPropertyChanging();
					this._AESERA = value;
					this.SendPropertyChanged("AESERA");
					this.OnAESERAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESDTH", DbType="Char(20)")]
		public string AESDTH
		{
			get
			{
				return this._AESDTH;
			}
			set
			{
				if ((this._AESDTH != value))
				{
					this.OnAESDTHChanging(value);
					this.SendPropertyChanging();
					this._AESDTH = value;
					this.SendPropertyChanged("AESDTH");
					this.OnAESDTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESLIFE", DbType="Char(20)")]
		public string AESLIFE
		{
			get
			{
				return this._AESLIFE;
			}
			set
			{
				if ((this._AESLIFE != value))
				{
					this.OnAESLIFEChanging(value);
					this.SendPropertyChanging();
					this._AESLIFE = value;
					this.SendPropertyChanged("AESLIFE");
					this.OnAESLIFEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESDISAB", DbType="Char(20)")]
		public string AESDISAB
		{
			get
			{
				return this._AESDISAB;
			}
			set
			{
				if ((this._AESDISAB != value))
				{
					this.OnAESDISABChanging(value);
					this.SendPropertyChanging();
					this._AESDISAB = value;
					this.SendPropertyChanged("AESDISAB");
					this.OnAESDISABChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESRHOS", DbType="Char(20)")]
		public string AESRHOS
		{
			get
			{
				return this._AESRHOS;
			}
			set
			{
				if ((this._AESRHOS != value))
				{
					this.OnAESRHOSChanging(value);
					this.SendPropertyChanging();
					this._AESRHOS = value;
					this.SendPropertyChanged("AESRHOS");
					this.OnAESRHOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESPHOS", DbType="Char(20)")]
		public string AESPHOS
		{
			get
			{
				return this._AESPHOS;
			}
			set
			{
				if ((this._AESPHOS != value))
				{
					this.OnAESPHOSChanging(value);
					this.SendPropertyChanging();
					this._AESPHOS = value;
					this.SendPropertyChanged("AESPHOS");
					this.OnAESPHOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESCONG", DbType="Char(20)")]
		public string AESCONG
		{
			get
			{
				return this._AESCONG;
			}
			set
			{
				if ((this._AESCONG != value))
				{
					this.OnAESCONGChanging(value);
					this.SendPropertyChanging();
					this._AESCONG = value;
					this.SendPropertyChanged("AESCONG");
					this.OnAESCONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESMIE", DbType="Char(20)")]
		public string AESMIE
		{
			get
			{
				return this._AESMIE;
			}
			set
			{
				if ((this._AESMIE != value))
				{
					this.OnAESMIEChanging(value);
					this.SendPropertyChanging();
					this._AESMIE = value;
					this.SendPropertyChanged("AESMIE");
					this.OnAESMIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESPI", DbType="Char(20)")]
		public string AESPI
		{
			get
			{
				return this._AESPI;
			}
			set
			{
				if ((this._AESPI != value))
				{
					this.OnAESPIChanging(value);
					this.SendPropertyChanging();
					this._AESPI = value;
					this.SendPropertyChanged("AESPI");
					this.OnAESPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEREL", DbType="Char(20)")]
		public string AEREL
		{
			get
			{
				return this._AEREL;
			}
			set
			{
				if ((this._AEREL != value))
				{
					this.OnAERELChanging(value);
					this.SendPropertyChanging();
					this._AEREL = value;
					this.SendPropertyChanged("AEREL");
					this.OnAERELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEFUP", DbType="Char(20)")]
		public string AEFUP
		{
			get
			{
				return this._AEFUP;
			}
			set
			{
				if ((this._AEFUP != value))
				{
					this.OnAEFUPChanging(value);
					this.SendPropertyChanging();
					this._AEFUP = value;
					this.SendPropertyChanged("AEFUP");
					this.OnAEFUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEX1", DbType="Char(200)")]
		public string AEX1
		{
			get
			{
				return this._AEX1;
			}
			set
			{
				if ((this._AEX1 != value))
				{
					this.OnAEX1Changing(value);
					this.SendPropertyChanging();
					this._AEX1 = value;
					this.SendPropertyChanged("AEX1");
					this.OnAEX1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISOUT", DbType="Char(20)")]
		public string VISOUT
		{
			get
			{
				return this._VISOUT;
			}
			set
			{
				if ((this._VISOUT != value))
				{
					this.OnVISOUTChanging(value);
					this.SendPropertyChanging();
					this._VISOUT = value;
					this.SendPropertyChanged("VISOUT");
					this.OnVISOUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINV", DbType="Char(20)")]
		public string TINV
		{
			get
			{
				return this._TINV;
			}
			set
			{
				if ((this._TINV != value))
				{
					this.OnTINVChanging(value);
					this.SendPropertyChanging();
					this._TINV = value;
					this.SendPropertyChanged("TINV");
					this.OnTINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPVIS", DbType="Char(20)")]
		public string GPVIS
		{
			get
			{
				return this._GPVIS;
			}
			set
			{
				if ((this._GPVIS != value))
				{
					this.OnGPVISChanging(value);
					this.SendPropertyChanging();
					this._GPVIS = value;
					this.SendPropertyChanged("GPVIS");
					this.OnGPVISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERS", DbType="Char(20)")]
		public string REFERS
		{
			get
			{
				return this._REFERS;
			}
			set
			{
				if ((this._REFERS != value))
				{
					this.OnREFERSChanging(value);
					this.SendPropertyChanging();
					this._REFERS = value;
					this.SendPropertyChanged("REFERS");
					this.OnREFERSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHYSIO", DbType="Char(20)")]
		public string PHYSIO
		{
			get
			{
				return this._PHYSIO;
			}
			set
			{
				if ((this._PHYSIO != value))
				{
					this.OnPHYSIOChanging(value);
					this.SendPropertyChanging();
					this._PHYSIO = value;
					this.SendPropertyChanged("PHYSIO");
					this.OnPHYSIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OCCTHP", DbType="Char(20)")]
		public string OCCTHP
		{
			get
			{
				return this._OCCTHP;
			}
			set
			{
				if ((this._OCCTHP != value))
				{
					this.OnOCCTHPChanging(value);
					this.SendPropertyChanging();
					this._OCCTHP = value;
					this.SendPropertyChanged("OCCTHP");
					this.OnOCCTHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NURSE", DbType="Char(20)")]
		public string NURSE
		{
			get
			{
				return this._NURSE;
			}
			set
			{
				if ((this._NURSE != value))
				{
					this.OnNURSEChanging(value);
					this.SendPropertyChanging();
					this._NURSE = value;
					this.SendPropertyChanged("NURSE");
					this.OnNURSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTH1", DbType="Char(20)")]
		public string OTH1
		{
			get
			{
				return this._OTH1;
			}
			set
			{
				if ((this._OTH1 != value))
				{
					this.OnOTH1Changing(value);
					this.SendPropertyChanging();
					this._OTH1 = value;
					this.SendPropertyChanged("OTH1");
					this.OnOTH1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEX2", DbType="Char(200)")]
		public string AEX2
		{
			get
			{
				return this._AEX2;
			}
			set
			{
				if ((this._AEX2 != value))
				{
					this.OnAEX2Changing(value);
					this.SendPropertyChanging();
					this._AEX2 = value;
					this.SendPropertyChanged("AEX2");
					this.OnAEX2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS1", DbType="Char(8)")]
		public string VISITS1
		{
			get
			{
				return this._VISITS1;
			}
			set
			{
				if ((this._VISITS1 != value))
				{
					this.OnVISITS1Changing(value);
					this.SendPropertyChanging();
					this._VISITS1 = value;
					this.SendPropertyChanged("VISITS1");
					this.OnVISITS1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS2", DbType="Char(8)")]
		public string VISITS2
		{
			get
			{
				return this._VISITS2;
			}
			set
			{
				if ((this._VISITS2 != value))
				{
					this.OnVISITS2Changing(value);
					this.SendPropertyChanging();
					this._VISITS2 = value;
					this.SendPropertyChanged("VISITS2");
					this.OnVISITS2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS3", DbType="Char(8)")]
		public string VISITS3
		{
			get
			{
				return this._VISITS3;
			}
			set
			{
				if ((this._VISITS3 != value))
				{
					this.OnVISITS3Changing(value);
					this.SendPropertyChanging();
					this._VISITS3 = value;
					this.SendPropertyChanged("VISITS3");
					this.OnVISITS3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS4", DbType="Char(8)")]
		public string VISITS4
		{
			get
			{
				return this._VISITS4;
			}
			set
			{
				if ((this._VISITS4 != value))
				{
					this.OnVISITS4Changing(value);
					this.SendPropertyChanging();
					this._VISITS4 = value;
					this.SendPropertyChanged("VISITS4");
					this.OnVISITS4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS5", DbType="Char(8)")]
		public string VISITS5
		{
			get
			{
				return this._VISITS5;
			}
			set
			{
				if ((this._VISITS5 != value))
				{
					this.OnVISITS5Changing(value);
					this.SendPropertyChanging();
					this._VISITS5 = value;
					this.SendPropertyChanged("VISITS5");
					this.OnVISITS5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS6", DbType="Char(8)")]
		public string VISITS6
		{
			get
			{
				return this._VISITS6;
			}
			set
			{
				if ((this._VISITS6 != value))
				{
					this.OnVISITS6Changing(value);
					this.SendPropertyChanging();
					this._VISITS6 = value;
					this.SendPropertyChanged("VISITS6");
					this.OnVISITS6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS7", DbType="Char(8)")]
		public string VISITS7
		{
			get
			{
				return this._VISITS7;
			}
			set
			{
				if ((this._VISITS7 != value))
				{
					this.OnVISITS7Changing(value);
					this.SendPropertyChanging();
					this._VISITS7 = value;
					this.SendPropertyChanged("VISITS7");
					this.OnVISITS7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXPRNC", DbType="Char(20)")]
		public string EXPRNC
		{
			get
			{
				return this._EXPRNC;
			}
			set
			{
				if ((this._EXPRNC != value))
				{
					this.OnEXPRNCChanging(value);
					this.SendPropertyChanging();
					this._EXPRNC = value;
					this.SendPropertyChanged("EXPRNC");
					this.OnEXPRNCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRISC", DbType="Char(20)")]
		public string MRISC
		{
			get
			{
				return this._MRISC;
			}
			set
			{
				if ((this._MRISC != value))
				{
					this.OnMRISCChanging(value);
					this.SendPropertyChanging();
					this._MRISC = value;
					this.SendPropertyChanged("MRISC");
					this.OnMRISCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTSCAN", DbType="Char(20)")]
		public string CTSCAN
		{
			get
			{
				return this._CTSCAN;
			}
			set
			{
				if ((this._CTSCAN != value))
				{
					this.OnCTSCANChanging(value);
					this.SendPropertyChanging();
					this._CTSCAN = value;
					this.SendPropertyChanged("CTSCAN");
					this.OnCTSCANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US", DbType="Char(20)")]
		public string US
		{
			get
			{
				return this._US;
			}
			set
			{
				if ((this._US != value))
				{
					this.OnUSChanging(value);
					this.SendPropertyChanging();
					this._US = value;
					this.SendPropertyChanged("US");
					this.OnUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XRAYB", DbType="Char(20)")]
		public string XRAYB
		{
			get
			{
				return this._XRAYB;
			}
			set
			{
				if ((this._XRAYB != value))
				{
					this.OnXRAYBChanging(value);
					this.SendPropertyChanging();
					this._XRAYB = value;
					this.SendPropertyChanged("XRAYB");
					this.OnXRAYBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTH2", DbType="Char(20)")]
		public string OTH2
		{
			get
			{
				return this._OTH2;
			}
			set
			{
				if ((this._OTH2 != value))
				{
					this.OnOTH2Changing(value);
					this.SendPropertyChanging();
					this._OTH2 = value;
					this.SendPropertyChanged("OTH2");
					this.OnOTH2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEX3", DbType="Char(200)")]
		public string AEX3
		{
			get
			{
				return this._AEX3;
			}
			set
			{
				if ((this._AEX3 != value))
				{
					this.OnAEX3Changing(value);
					this.SendPropertyChanging();
					this._AEX3 = value;
					this.SendPropertyChanged("AEX3");
					this.OnAEX3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADMISDT1", DbType="Char(9)")]
		public string ADMISDT1
		{
			get
			{
				return this._ADMISDT1;
			}
			set
			{
				if ((this._ADMISDT1 != value))
				{
					this.OnADMISDT1Changing(value);
					this.SendPropertyChanging();
					this._ADMISDT1 = value;
					this.SendPropertyChanged("ADMISDT1");
					this.OnADMISDT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCHDT1", DbType="Char(9)")]
		public string DISCHDT1
		{
			get
			{
				return this._DISCHDT1;
			}
			set
			{
				if ((this._DISCHDT1 != value))
				{
					this.OnDISCHDT1Changing(value);
					this.SendPropertyChanging();
					this._DISCHDT1 = value;
					this.SendPropertyChanged("DISCHDT1");
					this.OnDISCHDT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICUDYS1", DbType="Char(8)")]
		public string ICUDYS1
		{
			get
			{
				return this._ICUDYS1;
			}
			set
			{
				if ((this._ICUDYS1 != value))
				{
					this.OnICUDYS1Changing(value);
					this.SendPropertyChanging();
					this._ICUDYS1 = value;
					this.SendPropertyChanged("ICUDYS1");
					this.OnICUDYS1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMERG1", DbType="Char(20)")]
		public string EMERG1
		{
			get
			{
				return this._EMERG1;
			}
			set
			{
				if ((this._EMERG1 != value))
				{
					this.OnEMERG1Changing(value);
					this.SendPropertyChanging();
					this._EMERG1 = value;
					this.SendPropertyChanged("EMERG1");
					this.OnEMERG1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADMISDT2", DbType="Char(9)")]
		public string ADMISDT2
		{
			get
			{
				return this._ADMISDT2;
			}
			set
			{
				if ((this._ADMISDT2 != value))
				{
					this.OnADMISDT2Changing(value);
					this.SendPropertyChanging();
					this._ADMISDT2 = value;
					this.SendPropertyChanged("ADMISDT2");
					this.OnADMISDT2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCHDT2", DbType="Char(9)")]
		public string DISCHDT2
		{
			get
			{
				return this._DISCHDT2;
			}
			set
			{
				if ((this._DISCHDT2 != value))
				{
					this.OnDISCHDT2Changing(value);
					this.SendPropertyChanging();
					this._DISCHDT2 = value;
					this.SendPropertyChanged("DISCHDT2");
					this.OnDISCHDT2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICUDYS2", DbType="Char(8)")]
		public string ICUDYS2
		{
			get
			{
				return this._ICUDYS2;
			}
			set
			{
				if ((this._ICUDYS2 != value))
				{
					this.OnICUDYS2Changing(value);
					this.SendPropertyChanging();
					this._ICUDYS2 = value;
					this.SendPropertyChanged("ICUDYS2");
					this.OnICUDYS2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMERG2", DbType="Char(20)")]
		public string EMERG2
		{
			get
			{
				return this._EMERG2;
			}
			set
			{
				if ((this._EMERG2 != value))
				{
					this.OnEMERG2Changing(value);
					this.SendPropertyChanging();
					this._EMERG2 = value;
					this.SendPropertyChanged("EMERG2");
					this.OnEMERG2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADMISDT3", DbType="Char(9)")]
		public string ADMISDT3
		{
			get
			{
				return this._ADMISDT3;
			}
			set
			{
				if ((this._ADMISDT3 != value))
				{
					this.OnADMISDT3Changing(value);
					this.SendPropertyChanging();
					this._ADMISDT3 = value;
					this.SendPropertyChanged("ADMISDT3");
					this.OnADMISDT3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCHDT3", DbType="Char(9)")]
		public string DISCHDT3
		{
			get
			{
				return this._DISCHDT3;
			}
			set
			{
				if ((this._DISCHDT3 != value))
				{
					this.OnDISCHDT3Changing(value);
					this.SendPropertyChanging();
					this._DISCHDT3 = value;
					this.SendPropertyChanged("DISCHDT3");
					this.OnDISCHDT3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICUDYS3", DbType="Char(8)")]
		public string ICUDYS3
		{
			get
			{
				return this._ICUDYS3;
			}
			set
			{
				if ((this._ICUDYS3 != value))
				{
					this.OnICUDYS3Changing(value);
					this.SendPropertyChanging();
					this._ICUDYS3 = value;
					this.SendPropertyChanged("ICUDYS3");
					this.OnICUDYS3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMERG3", DbType="Char(20)")]
		public string EMERG3
		{
			get
			{
				return this._EMERG3;
			}
			set
			{
				if ((this._EMERG3 != value))
				{
					this.OnEMERG3Changing(value);
					this.SendPropertyChanging();
					this._EMERG3 = value;
					this.SendPropertyChanged("EMERG3");
					this.OnEMERG3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEX4", DbType="Char(200)")]
		public string AEX4
		{
			get
			{
				return this._AEX4;
			}
			set
			{
				if ((this._AEX4 != value))
				{
					this.OnAEX4Changing(value);
					this.SendPropertyChanging();
					this._AEX4 = value;
					this.SendPropertyChanged("AEX4");
					this.OnAEX4Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CD_BPSY")]
	public partial class CD_BPSY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RECORDID;
		
		private bool _ISVALID;
		
		private string _STUDY;
		
		private string _CENTRE;
		
		private string _PT;
		
		private string _ACTEVENT;
		
		private string _VDATE;
		
		private string _BIOPYN;
		
		private string _BIONYMD;
		
		private string _LESITE;
		
		private string _BIOCRER;
		
		private string _HISTCLN;
		
		private string _HISTX;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRECORDIDChanging(int value);
    partial void OnRECORDIDChanged();
    partial void OnISVALIDChanging(bool value);
    partial void OnISVALIDChanged();
    partial void OnSTUDYChanging(string value);
    partial void OnSTUDYChanged();
    partial void OnCENTREChanging(string value);
    partial void OnCENTREChanged();
    partial void OnPTChanging(string value);
    partial void OnPTChanged();
    partial void OnACTEVENTChanging(string value);
    partial void OnACTEVENTChanged();
    partial void OnVDATEChanging(string value);
    partial void OnVDATEChanged();
    partial void OnBIOPYNChanging(string value);
    partial void OnBIOPYNChanged();
    partial void OnBIONYMDChanging(string value);
    partial void OnBIONYMDChanged();
    partial void OnLESITEChanging(string value);
    partial void OnLESITEChanged();
    partial void OnBIOCRERChanging(string value);
    partial void OnBIOCRERChanged();
    partial void OnHISTCLNChanging(string value);
    partial void OnHISTCLNChanged();
    partial void OnHISTXChanging(string value);
    partial void OnHISTXChanged();
    #endregion
		
		public CD_BPSY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RECORDID
		{
			get
			{
				return this._RECORDID;
			}
			set
			{
				if ((this._RECORDID != value))
				{
					this.OnRECORDIDChanging(value);
					this.SendPropertyChanging();
					this._RECORDID = value;
					this.SendPropertyChanged("RECORDID");
					this.OnRECORDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISVALID", DbType="Bit NOT NULL")]
		public bool ISVALID
		{
			get
			{
				return this._ISVALID;
			}
			set
			{
				if ((this._ISVALID != value))
				{
					this.OnISVALIDChanging(value);
					this.SendPropertyChanging();
					this._ISVALID = value;
					this.SendPropertyChanged("ISVALID");
					this.OnISVALIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY", DbType="Char(9)")]
		public string STUDY
		{
			get
			{
				return this._STUDY;
			}
			set
			{
				if ((this._STUDY != value))
				{
					this.OnSTUDYChanging(value);
					this.SendPropertyChanging();
					this._STUDY = value;
					this.SendPropertyChanged("STUDY");
					this.OnSTUDYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRE", DbType="Char(5)")]
		public string CENTRE
		{
			get
			{
				return this._CENTRE;
			}
			set
			{
				if ((this._CENTRE != value))
				{
					this.OnCENTREChanging(value);
					this.SendPropertyChanging();
					this._CENTRE = value;
					this.SendPropertyChanged("CENTRE");
					this.OnCENTREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT", DbType="Char(10)")]
		public string PT
		{
			get
			{
				return this._PT;
			}
			set
			{
				if ((this._PT != value))
				{
					this.OnPTChanging(value);
					this.SendPropertyChanging();
					this._PT = value;
					this.SendPropertyChanged("PT");
					this.OnPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTEVENT", DbType="Char(8)")]
		public string ACTEVENT
		{
			get
			{
				return this._ACTEVENT;
			}
			set
			{
				if ((this._ACTEVENT != value))
				{
					this.OnACTEVENTChanging(value);
					this.SendPropertyChanging();
					this._ACTEVENT = value;
					this.SendPropertyChanged("ACTEVENT");
					this.OnACTEVENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VDATE", DbType="Char(9)")]
		public string VDATE
		{
			get
			{
				return this._VDATE;
			}
			set
			{
				if ((this._VDATE != value))
				{
					this.OnVDATEChanging(value);
					this.SendPropertyChanging();
					this._VDATE = value;
					this.SendPropertyChanged("VDATE");
					this.OnVDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIOPYN", DbType="Char(20)")]
		public string BIOPYN
		{
			get
			{
				return this._BIOPYN;
			}
			set
			{
				if ((this._BIOPYN != value))
				{
					this.OnBIOPYNChanging(value);
					this.SendPropertyChanging();
					this._BIOPYN = value;
					this.SendPropertyChanged("BIOPYN");
					this.OnBIOPYNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIONYMD", DbType="Char(9)")]
		public string BIONYMD
		{
			get
			{
				return this._BIONYMD;
			}
			set
			{
				if ((this._BIONYMD != value))
				{
					this.OnBIONYMDChanging(value);
					this.SendPropertyChanging();
					this._BIONYMD = value;
					this.SendPropertyChanged("BIONYMD");
					this.OnBIONYMDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LESITE", DbType="Char(20)")]
		public string LESITE
		{
			get
			{
				return this._LESITE;
			}
			set
			{
				if ((this._LESITE != value))
				{
					this.OnLESITEChanging(value);
					this.SendPropertyChanging();
					this._LESITE = value;
					this.SendPropertyChanged("LESITE");
					this.OnLESITEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIOCRER", DbType="Char(20)")]
		public string BIOCRER
		{
			get
			{
				return this._BIOCRER;
			}
			set
			{
				if ((this._BIOCRER != value))
				{
					this.OnBIOCRERChanging(value);
					this.SendPropertyChanging();
					this._BIOCRER = value;
					this.SendPropertyChanged("BIOCRER");
					this.OnBIOCRERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HISTCLN", DbType="Char(20)")]
		public string HISTCLN
		{
			get
			{
				return this._HISTCLN;
			}
			set
			{
				if ((this._HISTCLN != value))
				{
					this.OnHISTCLNChanging(value);
					this.SendPropertyChanging();
					this._HISTCLN = value;
					this.SendPropertyChanged("HISTCLN");
					this.OnHISTCLNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HISTX", DbType="Char(200)")]
		public string HISTX
		{
			get
			{
				return this._HISTX;
			}
			set
			{
				if ((this._HISTX != value))
				{
					this.OnHISTXChanging(value);
					this.SendPropertyChanging();
					this._HISTX = value;
					this.SendPropertyChanged("HISTX");
					this.OnHISTXChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CD_NDIS")]
	public partial class CD_NDI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RECORDID;
		
		private bool _ISVALID;
		
		private string _STUDY;
		
		private string _CENTRE;
		
		private string _PT;
		
		private string _VDATE;
		
		private string _NKDISC;
		
		private string _SURYMD;
		
		private string _SURGNM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRECORDIDChanging(int value);
    partial void OnRECORDIDChanged();
    partial void OnISVALIDChanging(bool value);
    partial void OnISVALIDChanged();
    partial void OnSTUDYChanging(string value);
    partial void OnSTUDYChanged();
    partial void OnCENTREChanging(string value);
    partial void OnCENTREChanged();
    partial void OnPTChanging(string value);
    partial void OnPTChanged();
    partial void OnVDATEChanging(string value);
    partial void OnVDATEChanged();
    partial void OnNKDISCChanging(string value);
    partial void OnNKDISCChanged();
    partial void OnSURYMDChanging(string value);
    partial void OnSURYMDChanged();
    partial void OnSURGNMChanging(string value);
    partial void OnSURGNMChanged();
    #endregion
		
		public CD_NDI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RECORDID
		{
			get
			{
				return this._RECORDID;
			}
			set
			{
				if ((this._RECORDID != value))
				{
					this.OnRECORDIDChanging(value);
					this.SendPropertyChanging();
					this._RECORDID = value;
					this.SendPropertyChanged("RECORDID");
					this.OnRECORDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISVALID", DbType="Bit NOT NULL")]
		public bool ISVALID
		{
			get
			{
				return this._ISVALID;
			}
			set
			{
				if ((this._ISVALID != value))
				{
					this.OnISVALIDChanging(value);
					this.SendPropertyChanging();
					this._ISVALID = value;
					this.SendPropertyChanged("ISVALID");
					this.OnISVALIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY", DbType="Char(9)")]
		public string STUDY
		{
			get
			{
				return this._STUDY;
			}
			set
			{
				if ((this._STUDY != value))
				{
					this.OnSTUDYChanging(value);
					this.SendPropertyChanging();
					this._STUDY = value;
					this.SendPropertyChanged("STUDY");
					this.OnSTUDYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRE", DbType="Char(5)")]
		public string CENTRE
		{
			get
			{
				return this._CENTRE;
			}
			set
			{
				if ((this._CENTRE != value))
				{
					this.OnCENTREChanging(value);
					this.SendPropertyChanging();
					this._CENTRE = value;
					this.SendPropertyChanged("CENTRE");
					this.OnCENTREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT", DbType="Char(10)")]
		public string PT
		{
			get
			{
				return this._PT;
			}
			set
			{
				if ((this._PT != value))
				{
					this.OnPTChanging(value);
					this.SendPropertyChanging();
					this._PT = value;
					this.SendPropertyChanged("PT");
					this.OnPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VDATE", DbType="Char(9)")]
		public string VDATE
		{
			get
			{
				return this._VDATE;
			}
			set
			{
				if ((this._VDATE != value))
				{
					this.OnVDATEChanging(value);
					this.SendPropertyChanging();
					this._VDATE = value;
					this.SendPropertyChanged("VDATE");
					this.OnVDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NKDISC", DbType="Char(20)")]
		public string NKDISC
		{
			get
			{
				return this._NKDISC;
			}
			set
			{
				if ((this._NKDISC != value))
				{
					this.OnNKDISCChanging(value);
					this.SendPropertyChanging();
					this._NKDISC = value;
					this.SendPropertyChanged("NKDISC");
					this.OnNKDISCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURYMD", DbType="Char(9)")]
		public string SURYMD
		{
			get
			{
				return this._SURYMD;
			}
			set
			{
				if ((this._SURYMD != value))
				{
					this.OnSURYMDChanging(value);
					this.SendPropertyChanging();
					this._SURYMD = value;
					this.SendPropertyChanged("SURYMD");
					this.OnSURYMDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURGNM", DbType="Char(50)")]
		public string SURGNM
		{
			get
			{
				return this._SURGNM;
			}
			set
			{
				if ((this._SURGNM != value))
				{
					this.OnSURGNMChanging(value);
					this.SendPropertyChanging();
					this._SURGNM = value;
					this.SendPropertyChanged("SURGNM");
					this.OnSURGNMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CD_PE")]
	public partial class CD_PE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RECORDID;
		
		private bool _ISVALID;
		
		private string _STUDY;
		
		private string _CENTRE;
		
		private string _PT;
		
		private string _ACTEVENT;
		
		private string _VDATE;
		
		private string _WTSTD;
		
		private string _ECOG;
		
		private string _SYS;
		
		private string _DIA;
		
		private string _PR;
		
		private string _PHYSC;
		
		private string _IMAGA;
		
		private string _BIOPYN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRECORDIDChanging(int value);
    partial void OnRECORDIDChanged();
    partial void OnISVALIDChanging(bool value);
    partial void OnISVALIDChanged();
    partial void OnSTUDYChanging(string value);
    partial void OnSTUDYChanged();
    partial void OnCENTREChanging(string value);
    partial void OnCENTREChanged();
    partial void OnPTChanging(string value);
    partial void OnPTChanged();
    partial void OnACTEVENTChanging(string value);
    partial void OnACTEVENTChanged();
    partial void OnVDATEChanging(string value);
    partial void OnVDATEChanged();
    partial void OnWTSTDChanging(string value);
    partial void OnWTSTDChanged();
    partial void OnECOGChanging(string value);
    partial void OnECOGChanged();
    partial void OnSYSChanging(string value);
    partial void OnSYSChanged();
    partial void OnDIAChanging(string value);
    partial void OnDIAChanged();
    partial void OnPRChanging(string value);
    partial void OnPRChanged();
    partial void OnPHYSCChanging(string value);
    partial void OnPHYSCChanged();
    partial void OnIMAGAChanging(string value);
    partial void OnIMAGAChanged();
    partial void OnBIOPYNChanging(string value);
    partial void OnBIOPYNChanged();
    #endregion
		
		public CD_PE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RECORDID
		{
			get
			{
				return this._RECORDID;
			}
			set
			{
				if ((this._RECORDID != value))
				{
					this.OnRECORDIDChanging(value);
					this.SendPropertyChanging();
					this._RECORDID = value;
					this.SendPropertyChanged("RECORDID");
					this.OnRECORDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISVALID", DbType="Bit NOT NULL")]
		public bool ISVALID
		{
			get
			{
				return this._ISVALID;
			}
			set
			{
				if ((this._ISVALID != value))
				{
					this.OnISVALIDChanging(value);
					this.SendPropertyChanging();
					this._ISVALID = value;
					this.SendPropertyChanged("ISVALID");
					this.OnISVALIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY", DbType="Char(9)")]
		public string STUDY
		{
			get
			{
				return this._STUDY;
			}
			set
			{
				if ((this._STUDY != value))
				{
					this.OnSTUDYChanging(value);
					this.SendPropertyChanging();
					this._STUDY = value;
					this.SendPropertyChanged("STUDY");
					this.OnSTUDYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRE", DbType="Char(5)")]
		public string CENTRE
		{
			get
			{
				return this._CENTRE;
			}
			set
			{
				if ((this._CENTRE != value))
				{
					this.OnCENTREChanging(value);
					this.SendPropertyChanging();
					this._CENTRE = value;
					this.SendPropertyChanged("CENTRE");
					this.OnCENTREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT", DbType="Char(10)")]
		public string PT
		{
			get
			{
				return this._PT;
			}
			set
			{
				if ((this._PT != value))
				{
					this.OnPTChanging(value);
					this.SendPropertyChanging();
					this._PT = value;
					this.SendPropertyChanged("PT");
					this.OnPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTEVENT", DbType="Char(8)")]
		public string ACTEVENT
		{
			get
			{
				return this._ACTEVENT;
			}
			set
			{
				if ((this._ACTEVENT != value))
				{
					this.OnACTEVENTChanging(value);
					this.SendPropertyChanging();
					this._ACTEVENT = value;
					this.SendPropertyChanged("ACTEVENT");
					this.OnACTEVENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VDATE", DbType="Char(9)")]
		public string VDATE
		{
			get
			{
				return this._VDATE;
			}
			set
			{
				if ((this._VDATE != value))
				{
					this.OnVDATEChanging(value);
					this.SendPropertyChanging();
					this._VDATE = value;
					this.SendPropertyChanged("VDATE");
					this.OnVDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WTSTD", DbType="Char(8)")]
		public string WTSTD
		{
			get
			{
				return this._WTSTD;
			}
			set
			{
				if ((this._WTSTD != value))
				{
					this.OnWTSTDChanging(value);
					this.SendPropertyChanging();
					this._WTSTD = value;
					this.SendPropertyChanged("WTSTD");
					this.OnWTSTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECOG", DbType="Char(8)")]
		public string ECOG
		{
			get
			{
				return this._ECOG;
			}
			set
			{
				if ((this._ECOG != value))
				{
					this.OnECOGChanging(value);
					this.SendPropertyChanging();
					this._ECOG = value;
					this.SendPropertyChanged("ECOG");
					this.OnECOGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS", DbType="Char(8)")]
		public string SYS
		{
			get
			{
				return this._SYS;
			}
			set
			{
				if ((this._SYS != value))
				{
					this.OnSYSChanging(value);
					this.SendPropertyChanging();
					this._SYS = value;
					this.SendPropertyChanged("SYS");
					this.OnSYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA", DbType="Char(8)")]
		public string DIA
		{
			get
			{
				return this._DIA;
			}
			set
			{
				if ((this._DIA != value))
				{
					this.OnDIAChanging(value);
					this.SendPropertyChanging();
					this._DIA = value;
					this.SendPropertyChanged("DIA");
					this.OnDIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR", DbType="Char(8)")]
		public string PR
		{
			get
			{
				return this._PR;
			}
			set
			{
				if ((this._PR != value))
				{
					this.OnPRChanging(value);
					this.SendPropertyChanging();
					this._PR = value;
					this.SendPropertyChanged("PR");
					this.OnPRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHYSC", DbType="Char(20)")]
		public string PHYSC
		{
			get
			{
				return this._PHYSC;
			}
			set
			{
				if ((this._PHYSC != value))
				{
					this.OnPHYSCChanging(value);
					this.SendPropertyChanging();
					this._PHYSC = value;
					this.SendPropertyChanged("PHYSC");
					this.OnPHYSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGA", DbType="Char(20)")]
		public string IMAGA
		{
			get
			{
				return this._IMAGA;
			}
			set
			{
				if ((this._IMAGA != value))
				{
					this.OnIMAGAChanging(value);
					this.SendPropertyChanging();
					this._IMAGA = value;
					this.SendPropertyChanged("IMAGA");
					this.OnIMAGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIOPYN", DbType="Char(20)")]
		public string BIOPYN
		{
			get
			{
				return this._BIOPYN;
			}
			set
			{
				if ((this._BIOPYN != value))
				{
					this.OnBIOPYNChanging(value);
					this.SendPropertyChanging();
					this._BIOPYN = value;
					this.SendPropertyChanged("BIOPYN");
					this.OnBIOPYNChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CD_ROR")]
	public partial class CD_ROR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RECORDID;
		
		private bool _ISVALID;
		
		private string _STUDY;
		
		private string _CENTRE;
		
		private string _PT;
		
		private string _VDATE;
		
		private string _TMRESD;
		
		private string _SURYMD;
		
		private string _SURGNM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRECORDIDChanging(int value);
    partial void OnRECORDIDChanged();
    partial void OnISVALIDChanging(bool value);
    partial void OnISVALIDChanged();
    partial void OnSTUDYChanging(string value);
    partial void OnSTUDYChanged();
    partial void OnCENTREChanging(string value);
    partial void OnCENTREChanged();
    partial void OnPTChanging(string value);
    partial void OnPTChanged();
    partial void OnVDATEChanging(string value);
    partial void OnVDATEChanged();
    partial void OnTMRESDChanging(string value);
    partial void OnTMRESDChanged();
    partial void OnSURYMDChanging(string value);
    partial void OnSURYMDChanged();
    partial void OnSURGNMChanging(string value);
    partial void OnSURGNMChanged();
    #endregion
		
		public CD_ROR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RECORDID
		{
			get
			{
				return this._RECORDID;
			}
			set
			{
				if ((this._RECORDID != value))
				{
					this.OnRECORDIDChanging(value);
					this.SendPropertyChanging();
					this._RECORDID = value;
					this.SendPropertyChanged("RECORDID");
					this.OnRECORDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISVALID", DbType="Bit NOT NULL")]
		public bool ISVALID
		{
			get
			{
				return this._ISVALID;
			}
			set
			{
				if ((this._ISVALID != value))
				{
					this.OnISVALIDChanging(value);
					this.SendPropertyChanging();
					this._ISVALID = value;
					this.SendPropertyChanged("ISVALID");
					this.OnISVALIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY", DbType="Char(9)")]
		public string STUDY
		{
			get
			{
				return this._STUDY;
			}
			set
			{
				if ((this._STUDY != value))
				{
					this.OnSTUDYChanging(value);
					this.SendPropertyChanging();
					this._STUDY = value;
					this.SendPropertyChanged("STUDY");
					this.OnSTUDYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRE", DbType="Char(5)")]
		public string CENTRE
		{
			get
			{
				return this._CENTRE;
			}
			set
			{
				if ((this._CENTRE != value))
				{
					this.OnCENTREChanging(value);
					this.SendPropertyChanging();
					this._CENTRE = value;
					this.SendPropertyChanged("CENTRE");
					this.OnCENTREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT", DbType="Char(10)")]
		public string PT
		{
			get
			{
				return this._PT;
			}
			set
			{
				if ((this._PT != value))
				{
					this.OnPTChanging(value);
					this.SendPropertyChanging();
					this._PT = value;
					this.SendPropertyChanged("PT");
					this.OnPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VDATE", DbType="Char(9)")]
		public string VDATE
		{
			get
			{
				return this._VDATE;
			}
			set
			{
				if ((this._VDATE != value))
				{
					this.OnVDATEChanging(value);
					this.SendPropertyChanging();
					this._VDATE = value;
					this.SendPropertyChanged("VDATE");
					this.OnVDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMRESD", DbType="Char(20)")]
		public string TMRESD
		{
			get
			{
				return this._TMRESD;
			}
			set
			{
				if ((this._TMRESD != value))
				{
					this.OnTMRESDChanging(value);
					this.SendPropertyChanging();
					this._TMRESD = value;
					this.SendPropertyChanged("TMRESD");
					this.OnTMRESDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURYMD", DbType="Char(9)")]
		public string SURYMD
		{
			get
			{
				return this._SURYMD;
			}
			set
			{
				if ((this._SURYMD != value))
				{
					this.OnSURYMDChanging(value);
					this.SendPropertyChanging();
					this._SURYMD = value;
					this.SendPropertyChanged("SURYMD");
					this.OnSURYMDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURGNM", DbType="Char(50)")]
		public string SURGNM
		{
			get
			{
				return this._SURGNM;
			}
			set
			{
				if ((this._SURGNM != value))
				{
					this.OnSURGNMChanging(value);
					this.SendPropertyChanging();
					this._SURGNM = value;
					this.SendPropertyChanged("SURGNM");
					this.OnSURGNMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
