#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMover_prod
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PSH_BOR1_003_1200_131_PROD_1")]
	public partial class PSH_ProdDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PSH_ProdDataContext() : 
				base(global::DataMover.Properties.Settings.Default.PSH_BOR1_003_1200_131_PROD_1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PSH_ProdDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PSH_ProdDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PSH_ProdDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PSH_ProdDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CD_AE> CD_AEs
		{
			get
			{
				return this.GetTable<CD_AE>();
			}
		}
		
		public System.Data.Linq.Table<CD_BPSY> CD_BPSies
		{
			get
			{
				return this.GetTable<CD_BPSY>();
			}
		}
		
		public System.Data.Linq.Table<CD_NDI> CD_NDIs
		{
			get
			{
				return this.GetTable<CD_NDI>();
			}
		}
		
		public System.Data.Linq.Table<CD_PE> CD_PEs
		{
			get
			{
				return this.GetTable<CD_PE>();
			}
		}
		
		public System.Data.Linq.Table<CD_ROR> CD_RORs
		{
			get
			{
				return this.GetTable<CD_ROR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CD_AE")]
	public partial class CD_AE
	{
		
		private int _RECORDID;
		
		private bool _ISVALID;
		
		private string _STUDY;
		
		private string _CENTRE;
		
		private string _PT;
		
		private string _AEMNM;
		
		private string _AEONDT;
		
		private string _AEENDDT;
		
		private string _AEOUT;
		
		private string _AETHPA;
		
		private string _CTCAE;
		
		private string _AEACTE;
		
		private string _AERDTOX;
		
		private string _AESERA;
		
		private string _AESDTH;
		
		private string _AESLIFE;
		
		private string _AESDISAB;
		
		private string _AESRHOS;
		
		private string _AESPHOS;
		
		private string _AESCONG;
		
		private string _AESMIE;
		
		private string _AESPI;
		
		private string _AEREL;
		
		private string _AEFUP;
		
		private string _AEX1;
		
		private string _VISOUT;
		
		private string _TINV;
		
		private string _GPVIS;
		
		private string _REFERS;
		
		private string _PHYSIO;
		
		private string _OCCTHP;
		
		private string _NURSE;
		
		private string _OTH1;
		
		private string _AEX2;
		
		private string _VISITS1;
		
		private string _VISITS2;
		
		private string _VISITS3;
		
		private string _VISITS4;
		
		private string _VISITS5;
		
		private string _VISITS6;
		
		private string _VISITS7;
		
		private string _EXPRNC;
		
		private string _MRISC;
		
		private string _CTSCAN;
		
		private string _US;
		
		private string _XRAYB;
		
		private string _OTH2;
		
		private string _AEX3;
		
		private string _ADMISDT1;
		
		private string _DISCHDT1;
		
		private string _ICUDYS1;
		
		private string _EMERG1;
		
		private string _ADMISDT2;
		
		private string _DISCHDT2;
		
		private string _ICUDYS2;
		
		private string _EMERG2;
		
		private string _ADMISDT3;
		
		private string _DISCHDT3;
		
		private string _ICUDYS3;
		
		private string _EMERG3;
		
		private string _AEX4;
		
		public CD_AE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int RECORDID
		{
			get
			{
				return this._RECORDID;
			}
			set
			{
				if ((this._RECORDID != value))
				{
					this._RECORDID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISVALID", DbType="Bit NOT NULL")]
		public bool ISVALID
		{
			get
			{
				return this._ISVALID;
			}
			set
			{
				if ((this._ISVALID != value))
				{
					this._ISVALID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY", DbType="Char(9)")]
		public string STUDY
		{
			get
			{
				return this._STUDY;
			}
			set
			{
				if ((this._STUDY != value))
				{
					this._STUDY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRE", DbType="Char(5)")]
		public string CENTRE
		{
			get
			{
				return this._CENTRE;
			}
			set
			{
				if ((this._CENTRE != value))
				{
					this._CENTRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT", DbType="Char(10)")]
		public string PT
		{
			get
			{
				return this._PT;
			}
			set
			{
				if ((this._PT != value))
				{
					this._PT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEMNM", DbType="Char(50)")]
		public string AEMNM
		{
			get
			{
				return this._AEMNM;
			}
			set
			{
				if ((this._AEMNM != value))
				{
					this._AEMNM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEONDT", DbType="Char(9)")]
		public string AEONDT
		{
			get
			{
				return this._AEONDT;
			}
			set
			{
				if ((this._AEONDT != value))
				{
					this._AEONDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEENDDT", DbType="Char(9)")]
		public string AEENDDT
		{
			get
			{
				return this._AEENDDT;
			}
			set
			{
				if ((this._AEENDDT != value))
				{
					this._AEENDDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEOUT", DbType="Char(20)")]
		public string AEOUT
		{
			get
			{
				return this._AEOUT;
			}
			set
			{
				if ((this._AEOUT != value))
				{
					this._AEOUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AETHPA", DbType="Char(20)")]
		public string AETHPA
		{
			get
			{
				return this._AETHPA;
			}
			set
			{
				if ((this._AETHPA != value))
				{
					this._AETHPA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTCAE", DbType="Char(20)")]
		public string CTCAE
		{
			get
			{
				return this._CTCAE;
			}
			set
			{
				if ((this._CTCAE != value))
				{
					this._CTCAE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEACTE", DbType="Char(20)")]
		public string AEACTE
		{
			get
			{
				return this._AEACTE;
			}
			set
			{
				if ((this._AEACTE != value))
				{
					this._AEACTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AERDTOX", DbType="Char(20)")]
		public string AERDTOX
		{
			get
			{
				return this._AERDTOX;
			}
			set
			{
				if ((this._AERDTOX != value))
				{
					this._AERDTOX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESERA", DbType="Char(20)")]
		public string AESERA
		{
			get
			{
				return this._AESERA;
			}
			set
			{
				if ((this._AESERA != value))
				{
					this._AESERA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESDTH", DbType="Char(20)")]
		public string AESDTH
		{
			get
			{
				return this._AESDTH;
			}
			set
			{
				if ((this._AESDTH != value))
				{
					this._AESDTH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESLIFE", DbType="Char(20)")]
		public string AESLIFE
		{
			get
			{
				return this._AESLIFE;
			}
			set
			{
				if ((this._AESLIFE != value))
				{
					this._AESLIFE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESDISAB", DbType="Char(20)")]
		public string AESDISAB
		{
			get
			{
				return this._AESDISAB;
			}
			set
			{
				if ((this._AESDISAB != value))
				{
					this._AESDISAB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESRHOS", DbType="Char(20)")]
		public string AESRHOS
		{
			get
			{
				return this._AESRHOS;
			}
			set
			{
				if ((this._AESRHOS != value))
				{
					this._AESRHOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESPHOS", DbType="Char(20)")]
		public string AESPHOS
		{
			get
			{
				return this._AESPHOS;
			}
			set
			{
				if ((this._AESPHOS != value))
				{
					this._AESPHOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESCONG", DbType="Char(20)")]
		public string AESCONG
		{
			get
			{
				return this._AESCONG;
			}
			set
			{
				if ((this._AESCONG != value))
				{
					this._AESCONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESMIE", DbType="Char(20)")]
		public string AESMIE
		{
			get
			{
				return this._AESMIE;
			}
			set
			{
				if ((this._AESMIE != value))
				{
					this._AESMIE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AESPI", DbType="Char(20)")]
		public string AESPI
		{
			get
			{
				return this._AESPI;
			}
			set
			{
				if ((this._AESPI != value))
				{
					this._AESPI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEREL", DbType="Char(20)")]
		public string AEREL
		{
			get
			{
				return this._AEREL;
			}
			set
			{
				if ((this._AEREL != value))
				{
					this._AEREL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEFUP", DbType="Char(20)")]
		public string AEFUP
		{
			get
			{
				return this._AEFUP;
			}
			set
			{
				if ((this._AEFUP != value))
				{
					this._AEFUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEX1", DbType="Char(200)")]
		public string AEX1
		{
			get
			{
				return this._AEX1;
			}
			set
			{
				if ((this._AEX1 != value))
				{
					this._AEX1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISOUT", DbType="Char(20)")]
		public string VISOUT
		{
			get
			{
				return this._VISOUT;
			}
			set
			{
				if ((this._VISOUT != value))
				{
					this._VISOUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINV", DbType="Char(20)")]
		public string TINV
		{
			get
			{
				return this._TINV;
			}
			set
			{
				if ((this._TINV != value))
				{
					this._TINV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPVIS", DbType="Char(20)")]
		public string GPVIS
		{
			get
			{
				return this._GPVIS;
			}
			set
			{
				if ((this._GPVIS != value))
				{
					this._GPVIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERS", DbType="Char(20)")]
		public string REFERS
		{
			get
			{
				return this._REFERS;
			}
			set
			{
				if ((this._REFERS != value))
				{
					this._REFERS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHYSIO", DbType="Char(20)")]
		public string PHYSIO
		{
			get
			{
				return this._PHYSIO;
			}
			set
			{
				if ((this._PHYSIO != value))
				{
					this._PHYSIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OCCTHP", DbType="Char(20)")]
		public string OCCTHP
		{
			get
			{
				return this._OCCTHP;
			}
			set
			{
				if ((this._OCCTHP != value))
				{
					this._OCCTHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NURSE", DbType="Char(20)")]
		public string NURSE
		{
			get
			{
				return this._NURSE;
			}
			set
			{
				if ((this._NURSE != value))
				{
					this._NURSE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTH1", DbType="Char(20)")]
		public string OTH1
		{
			get
			{
				return this._OTH1;
			}
			set
			{
				if ((this._OTH1 != value))
				{
					this._OTH1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEX2", DbType="Char(200)")]
		public string AEX2
		{
			get
			{
				return this._AEX2;
			}
			set
			{
				if ((this._AEX2 != value))
				{
					this._AEX2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS1", DbType="Char(8)")]
		public string VISITS1
		{
			get
			{
				return this._VISITS1;
			}
			set
			{
				if ((this._VISITS1 != value))
				{
					this._VISITS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS2", DbType="Char(8)")]
		public string VISITS2
		{
			get
			{
				return this._VISITS2;
			}
			set
			{
				if ((this._VISITS2 != value))
				{
					this._VISITS2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS3", DbType="Char(8)")]
		public string VISITS3
		{
			get
			{
				return this._VISITS3;
			}
			set
			{
				if ((this._VISITS3 != value))
				{
					this._VISITS3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS4", DbType="Char(8)")]
		public string VISITS4
		{
			get
			{
				return this._VISITS4;
			}
			set
			{
				if ((this._VISITS4 != value))
				{
					this._VISITS4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS5", DbType="Char(8)")]
		public string VISITS5
		{
			get
			{
				return this._VISITS5;
			}
			set
			{
				if ((this._VISITS5 != value))
				{
					this._VISITS5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS6", DbType="Char(8)")]
		public string VISITS6
		{
			get
			{
				return this._VISITS6;
			}
			set
			{
				if ((this._VISITS6 != value))
				{
					this._VISITS6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISITS7", DbType="Char(8)")]
		public string VISITS7
		{
			get
			{
				return this._VISITS7;
			}
			set
			{
				if ((this._VISITS7 != value))
				{
					this._VISITS7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXPRNC", DbType="Char(20)")]
		public string EXPRNC
		{
			get
			{
				return this._EXPRNC;
			}
			set
			{
				if ((this._EXPRNC != value))
				{
					this._EXPRNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRISC", DbType="Char(20)")]
		public string MRISC
		{
			get
			{
				return this._MRISC;
			}
			set
			{
				if ((this._MRISC != value))
				{
					this._MRISC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTSCAN", DbType="Char(20)")]
		public string CTSCAN
		{
			get
			{
				return this._CTSCAN;
			}
			set
			{
				if ((this._CTSCAN != value))
				{
					this._CTSCAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US", DbType="Char(20)")]
		public string US
		{
			get
			{
				return this._US;
			}
			set
			{
				if ((this._US != value))
				{
					this._US = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XRAYB", DbType="Char(20)")]
		public string XRAYB
		{
			get
			{
				return this._XRAYB;
			}
			set
			{
				if ((this._XRAYB != value))
				{
					this._XRAYB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTH2", DbType="Char(20)")]
		public string OTH2
		{
			get
			{
				return this._OTH2;
			}
			set
			{
				if ((this._OTH2 != value))
				{
					this._OTH2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEX3", DbType="Char(200)")]
		public string AEX3
		{
			get
			{
				return this._AEX3;
			}
			set
			{
				if ((this._AEX3 != value))
				{
					this._AEX3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADMISDT1", DbType="Char(9)")]
		public string ADMISDT1
		{
			get
			{
				return this._ADMISDT1;
			}
			set
			{
				if ((this._ADMISDT1 != value))
				{
					this._ADMISDT1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCHDT1", DbType="Char(9)")]
		public string DISCHDT1
		{
			get
			{
				return this._DISCHDT1;
			}
			set
			{
				if ((this._DISCHDT1 != value))
				{
					this._DISCHDT1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICUDYS1", DbType="Char(8)")]
		public string ICUDYS1
		{
			get
			{
				return this._ICUDYS1;
			}
			set
			{
				if ((this._ICUDYS1 != value))
				{
					this._ICUDYS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMERG1", DbType="Char(20)")]
		public string EMERG1
		{
			get
			{
				return this._EMERG1;
			}
			set
			{
				if ((this._EMERG1 != value))
				{
					this._EMERG1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADMISDT2", DbType="Char(9)")]
		public string ADMISDT2
		{
			get
			{
				return this._ADMISDT2;
			}
			set
			{
				if ((this._ADMISDT2 != value))
				{
					this._ADMISDT2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCHDT2", DbType="Char(9)")]
		public string DISCHDT2
		{
			get
			{
				return this._DISCHDT2;
			}
			set
			{
				if ((this._DISCHDT2 != value))
				{
					this._DISCHDT2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICUDYS2", DbType="Char(8)")]
		public string ICUDYS2
		{
			get
			{
				return this._ICUDYS2;
			}
			set
			{
				if ((this._ICUDYS2 != value))
				{
					this._ICUDYS2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMERG2", DbType="Char(20)")]
		public string EMERG2
		{
			get
			{
				return this._EMERG2;
			}
			set
			{
				if ((this._EMERG2 != value))
				{
					this._EMERG2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADMISDT3", DbType="Char(9)")]
		public string ADMISDT3
		{
			get
			{
				return this._ADMISDT3;
			}
			set
			{
				if ((this._ADMISDT3 != value))
				{
					this._ADMISDT3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCHDT3", DbType="Char(9)")]
		public string DISCHDT3
		{
			get
			{
				return this._DISCHDT3;
			}
			set
			{
				if ((this._DISCHDT3 != value))
				{
					this._DISCHDT3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICUDYS3", DbType="Char(8)")]
		public string ICUDYS3
		{
			get
			{
				return this._ICUDYS3;
			}
			set
			{
				if ((this._ICUDYS3 != value))
				{
					this._ICUDYS3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMERG3", DbType="Char(20)")]
		public string EMERG3
		{
			get
			{
				return this._EMERG3;
			}
			set
			{
				if ((this._EMERG3 != value))
				{
					this._EMERG3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEX4", DbType="Char(200)")]
		public string AEX4
		{
			get
			{
				return this._AEX4;
			}
			set
			{
				if ((this._AEX4 != value))
				{
					this._AEX4 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CD_BPSY")]
	public partial class CD_BPSY
	{
		
		private int _RECORDID;
		
		private bool _ISVALID;
		
		private string _STUDY;
		
		private string _CENTRE;
		
		private string _PT;
		
		private string _ACTEVENT;
		
		private string _VDATE;
		
		private string _BIOPYN;
		
		private string _BIONYMD;
		
		private string _LESITE;
		
		private string _BIOCRER;
		
		private string _HISTCLN;
		
		private string _HISTX;
		
		public CD_BPSY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int RECORDID
		{
			get
			{
				return this._RECORDID;
			}
			set
			{
				if ((this._RECORDID != value))
				{
					this._RECORDID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISVALID", DbType="Bit NOT NULL")]
		public bool ISVALID
		{
			get
			{
				return this._ISVALID;
			}
			set
			{
				if ((this._ISVALID != value))
				{
					this._ISVALID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY", DbType="Char(9)")]
		public string STUDY
		{
			get
			{
				return this._STUDY;
			}
			set
			{
				if ((this._STUDY != value))
				{
					this._STUDY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRE", DbType="Char(5)")]
		public string CENTRE
		{
			get
			{
				return this._CENTRE;
			}
			set
			{
				if ((this._CENTRE != value))
				{
					this._CENTRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT", DbType="Char(10)")]
		public string PT
		{
			get
			{
				return this._PT;
			}
			set
			{
				if ((this._PT != value))
				{
					this._PT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTEVENT", DbType="Char(8)")]
		public string ACTEVENT
		{
			get
			{
				return this._ACTEVENT;
			}
			set
			{
				if ((this._ACTEVENT != value))
				{
					this._ACTEVENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VDATE", DbType="Char(9)")]
		public string VDATE
		{
			get
			{
				return this._VDATE;
			}
			set
			{
				if ((this._VDATE != value))
				{
					this._VDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIOPYN", DbType="Char(20)")]
		public string BIOPYN
		{
			get
			{
				return this._BIOPYN;
			}
			set
			{
				if ((this._BIOPYN != value))
				{
					this._BIOPYN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIONYMD", DbType="Char(9)")]
		public string BIONYMD
		{
			get
			{
				return this._BIONYMD;
			}
			set
			{
				if ((this._BIONYMD != value))
				{
					this._BIONYMD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LESITE", DbType="Char(20)")]
		public string LESITE
		{
			get
			{
				return this._LESITE;
			}
			set
			{
				if ((this._LESITE != value))
				{
					this._LESITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIOCRER", DbType="Char(20)")]
		public string BIOCRER
		{
			get
			{
				return this._BIOCRER;
			}
			set
			{
				if ((this._BIOCRER != value))
				{
					this._BIOCRER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HISTCLN", DbType="Char(20)")]
		public string HISTCLN
		{
			get
			{
				return this._HISTCLN;
			}
			set
			{
				if ((this._HISTCLN != value))
				{
					this._HISTCLN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HISTX", DbType="Char(200)")]
		public string HISTX
		{
			get
			{
				return this._HISTX;
			}
			set
			{
				if ((this._HISTX != value))
				{
					this._HISTX = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CD_NDIS")]
	public partial class CD_NDI
	{
		
		private int _RECORDID;
		
		private bool _ISVALID;
		
		private string _STUDY;
		
		private string _CENTRE;
		
		private string _PT;
		
		private string _VDATE;
		
		private string _NKDISC;
		
		private string _SURYMD;
		
		private string _SURGNM;
		
		public CD_NDI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int RECORDID
		{
			get
			{
				return this._RECORDID;
			}
			set
			{
				if ((this._RECORDID != value))
				{
					this._RECORDID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISVALID", DbType="Bit NOT NULL")]
		public bool ISVALID
		{
			get
			{
				return this._ISVALID;
			}
			set
			{
				if ((this._ISVALID != value))
				{
					this._ISVALID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY", DbType="Char(9)")]
		public string STUDY
		{
			get
			{
				return this._STUDY;
			}
			set
			{
				if ((this._STUDY != value))
				{
					this._STUDY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRE", DbType="Char(5)")]
		public string CENTRE
		{
			get
			{
				return this._CENTRE;
			}
			set
			{
				if ((this._CENTRE != value))
				{
					this._CENTRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT", DbType="Char(10)")]
		public string PT
		{
			get
			{
				return this._PT;
			}
			set
			{
				if ((this._PT != value))
				{
					this._PT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VDATE", DbType="Char(9)")]
		public string VDATE
		{
			get
			{
				return this._VDATE;
			}
			set
			{
				if ((this._VDATE != value))
				{
					this._VDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NKDISC", DbType="Char(20)")]
		public string NKDISC
		{
			get
			{
				return this._NKDISC;
			}
			set
			{
				if ((this._NKDISC != value))
				{
					this._NKDISC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURYMD", DbType="Char(9)")]
		public string SURYMD
		{
			get
			{
				return this._SURYMD;
			}
			set
			{
				if ((this._SURYMD != value))
				{
					this._SURYMD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURGNM", DbType="Char(50)")]
		public string SURGNM
		{
			get
			{
				return this._SURGNM;
			}
			set
			{
				if ((this._SURGNM != value))
				{
					this._SURGNM = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CD_PE")]
	public partial class CD_PE
	{
		
		private int _RECORDID;
		
		private bool _ISVALID;
		
		private string _STUDY;
		
		private string _CENTRE;
		
		private string _PT;
		
		private string _ACTEVENT;
		
		private string _VDATE;
		
		private string _WTSTD;
		
		private string _ECOG;
		
		private string _SYS;
		
		private string _DIA;
		
		private string _PR;
		
		private string _PHYSC;
		
		private string _IMAGA;
		
		private string _BIOPYN;
		
		public CD_PE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int RECORDID
		{
			get
			{
				return this._RECORDID;
			}
			set
			{
				if ((this._RECORDID != value))
				{
					this._RECORDID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISVALID", DbType="Bit NOT NULL")]
		public bool ISVALID
		{
			get
			{
				return this._ISVALID;
			}
			set
			{
				if ((this._ISVALID != value))
				{
					this._ISVALID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY", DbType="Char(9)")]
		public string STUDY
		{
			get
			{
				return this._STUDY;
			}
			set
			{
				if ((this._STUDY != value))
				{
					this._STUDY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRE", DbType="Char(5)")]
		public string CENTRE
		{
			get
			{
				return this._CENTRE;
			}
			set
			{
				if ((this._CENTRE != value))
				{
					this._CENTRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT", DbType="Char(10)")]
		public string PT
		{
			get
			{
				return this._PT;
			}
			set
			{
				if ((this._PT != value))
				{
					this._PT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTEVENT", DbType="Char(8)")]
		public string ACTEVENT
		{
			get
			{
				return this._ACTEVENT;
			}
			set
			{
				if ((this._ACTEVENT != value))
				{
					this._ACTEVENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VDATE", DbType="Char(9)")]
		public string VDATE
		{
			get
			{
				return this._VDATE;
			}
			set
			{
				if ((this._VDATE != value))
				{
					this._VDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WTSTD", DbType="Char(8)")]
		public string WTSTD
		{
			get
			{
				return this._WTSTD;
			}
			set
			{
				if ((this._WTSTD != value))
				{
					this._WTSTD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECOG", DbType="Char(8)")]
		public string ECOG
		{
			get
			{
				return this._ECOG;
			}
			set
			{
				if ((this._ECOG != value))
				{
					this._ECOG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS", DbType="Char(8)")]
		public string SYS
		{
			get
			{
				return this._SYS;
			}
			set
			{
				if ((this._SYS != value))
				{
					this._SYS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA", DbType="Char(8)")]
		public string DIA
		{
			get
			{
				return this._DIA;
			}
			set
			{
				if ((this._DIA != value))
				{
					this._DIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR", DbType="Char(8)")]
		public string PR
		{
			get
			{
				return this._PR;
			}
			set
			{
				if ((this._PR != value))
				{
					this._PR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHYSC", DbType="Char(20)")]
		public string PHYSC
		{
			get
			{
				return this._PHYSC;
			}
			set
			{
				if ((this._PHYSC != value))
				{
					this._PHYSC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGA", DbType="Char(20)")]
		public string IMAGA
		{
			get
			{
				return this._IMAGA;
			}
			set
			{
				if ((this._IMAGA != value))
				{
					this._IMAGA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIOPYN", DbType="Char(20)")]
		public string BIOPYN
		{
			get
			{
				return this._BIOPYN;
			}
			set
			{
				if ((this._BIOPYN != value))
				{
					this._BIOPYN = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CD_ROR")]
	public partial class CD_ROR
	{
		
		private int _RECORDID;
		
		private bool _ISVALID;
		
		private string _STUDY;
		
		private string _CENTRE;
		
		private string _PT;
		
		private string _VDATE;
		
		private string _TMRESD;
		
		private string _SURYMD;
		
		private string _SURGNM;
		
		public CD_ROR()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int RECORDID
		{
			get
			{
				return this._RECORDID;
			}
			set
			{
				if ((this._RECORDID != value))
				{
					this._RECORDID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISVALID", DbType="Bit NOT NULL")]
		public bool ISVALID
		{
			get
			{
				return this._ISVALID;
			}
			set
			{
				if ((this._ISVALID != value))
				{
					this._ISVALID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY", DbType="Char(9)")]
		public string STUDY
		{
			get
			{
				return this._STUDY;
			}
			set
			{
				if ((this._STUDY != value))
				{
					this._STUDY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRE", DbType="Char(5)")]
		public string CENTRE
		{
			get
			{
				return this._CENTRE;
			}
			set
			{
				if ((this._CENTRE != value))
				{
					this._CENTRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT", DbType="Char(10)")]
		public string PT
		{
			get
			{
				return this._PT;
			}
			set
			{
				if ((this._PT != value))
				{
					this._PT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VDATE", DbType="Char(9)")]
		public string VDATE
		{
			get
			{
				return this._VDATE;
			}
			set
			{
				if ((this._VDATE != value))
				{
					this._VDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMRESD", DbType="Char(20)")]
		public string TMRESD
		{
			get
			{
				return this._TMRESD;
			}
			set
			{
				if ((this._TMRESD != value))
				{
					this._TMRESD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURYMD", DbType="Char(9)")]
		public string SURYMD
		{
			get
			{
				return this._SURYMD;
			}
			set
			{
				if ((this._SURYMD != value))
				{
					this._SURYMD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURGNM", DbType="Char(50)")]
		public string SURGNM
		{
			get
			{
				return this._SURGNM;
			}
			set
			{
				if ((this._SURGNM != value))
				{
					this._SURGNM = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
