//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebugTest.PIERService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PIERService.IPIERService")]
    public interface IPIERService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/StartSession", ReplyAction="http://tempuri.org/IPIERService/StartSessionResponse")]
        DebugTest.PIERService.StartSessionResponse StartSession(DebugTest.PIERService.StartSessionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/StartSession", ReplyAction="http://tempuri.org/IPIERService/StartSessionResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.StartSessionResponse> StartSessionAsync(DebugTest.PIERService.StartSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectRecords", ReplyAction="http://tempuri.org/IPIERService/GetSubjectRecordsResponse")]
        DebugTest.PIERService.GetSubjectRecordsResponse GetSubjectRecords(DebugTest.PIERService.GetSubjectRecordsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectRecords", ReplyAction="http://tempuri.org/IPIERService/GetSubjectRecordsResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectRecordsResponse> GetSubjectRecordsAsync(DebugTest.PIERService.GetSubjectRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectClinicalDataRecords", ReplyAction="http://tempuri.org/IPIERService/GetSubjectClinicalDataRecordsResponse")]
        DebugTest.PIERService.GetSubjectClinicalDataRecordsResponse GetSubjectClinicalDataRecords(DebugTest.PIERService.GetSubjectClinicalDataRecordsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectClinicalDataRecords", ReplyAction="http://tempuri.org/IPIERService/GetSubjectClinicalDataRecordsResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectClinicalDataRecordsResponse> GetSubjectClinicalDataRecordsAsync(DebugTest.PIERService.GetSubjectClinicalDataRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectVisitClinicalDataRecords", ReplyAction="http://tempuri.org/IPIERService/GetSubjectVisitClinicalDataRecordsResponse")]
        DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsResponse GetSubjectVisitClinicalDataRecords(DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectVisitClinicalDataRecords", ReplyAction="http://tempuri.org/IPIERService/GetSubjectVisitClinicalDataRecordsResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsResponse> GetSubjectVisitClinicalDataRecordsAsync(DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectVisitUnReadClinicalDataRecords", ReplyAction="http://tempuri.org/IPIERService/GetSubjectVisitUnReadClinicalDataRecordsResponse")]
        DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsResponse GetSubjectVisitUnReadClinicalDataRecords(DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectVisitUnReadClinicalDataRecords", ReplyAction="http://tempuri.org/IPIERService/GetSubjectVisitUnReadClinicalDataRecordsResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsResponse> GetSubjectVisitUnReadClinicalDataRecordsAsync(DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/SetSubjectVisitAsRead", ReplyAction="http://tempuri.org/IPIERService/SetSubjectVisitAsReadResponse")]
        DebugTest.PIERService.SetSubjectVisitAsReadResponse SetSubjectVisitAsRead(DebugTest.PIERService.SetSubjectVisitAsReadRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/SetSubjectVisitAsRead", ReplyAction="http://tempuri.org/IPIERService/SetSubjectVisitAsReadResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.SetSubjectVisitAsReadResponse> SetSubjectVisitAsReadAsync(DebugTest.PIERService.SetSubjectVisitAsReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/SetClinicalDataRecordsAsRead", ReplyAction="http://tempuri.org/IPIERService/SetClinicalDataRecordsAsReadResponse")]
        DebugTest.PIERService.SetClinicalDataRecordsAsReadResponse SetClinicalDataRecordsAsRead(DebugTest.PIERService.SetClinicalDataRecordsAsReadRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/SetClinicalDataRecordsAsRead", ReplyAction="http://tempuri.org/IPIERService/SetClinicalDataRecordsAsReadResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.SetClinicalDataRecordsAsReadResponse> SetClinicalDataRecordsAsReadAsync(DebugTest.PIERService.SetClinicalDataRecordsAsReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/StartSessionUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/StartSessionUsingHMACResponse")]
        DebugTest.PIERService.StartSessionUsingHMACResponse StartSessionUsingHMAC(DebugTest.PIERService.StartSessionUsingHMACRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/StartSessionUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/StartSessionUsingHMACResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.StartSessionUsingHMACResponse> StartSessionUsingHMACAsync(DebugTest.PIERService.StartSessionUsingHMACRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetLatestUserSessionKeyUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/GetLatestUserSessionKeyUsingHMACResponse")]
        DebugTest.PIERService.GetLatestUserSessionKeyUsingHMACResponse GetLatestUserSessionKeyUsingHMAC(DebugTest.PIERService.GetLatestUserSessionKeyUsingHMACRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetLatestUserSessionKeyUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/GetLatestUserSessionKeyUsingHMACResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.GetLatestUserSessionKeyUsingHMACResponse> GetLatestUserSessionKeyUsingHMACAsync(DebugTest.PIERService.GetLatestUserSessionKeyUsingHMACRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectRecordsUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/GetSubjectRecordsUsingHMACResponse")]
        DebugTest.PIERService.GetSubjectRecordsUsingHMACResponse GetSubjectRecordsUsingHMAC(DebugTest.PIERService.GetSubjectRecordsUsingHMACRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectRecordsUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/GetSubjectRecordsUsingHMACResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectRecordsUsingHMACResponse> GetSubjectRecordsUsingHMACAsync(DebugTest.PIERService.GetSubjectRecordsUsingHMACRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectVisitClinicalDataRecordsUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/GetSubjectVisitClinicalDataRecordsUsingHMACRespon" +
            "se")]
        DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsUsingHMACResponse GetSubjectVisitClinicalDataRecordsUsingHMAC(DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsUsingHMACRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectVisitClinicalDataRecordsUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/GetSubjectVisitClinicalDataRecordsUsingHMACRespon" +
            "se")]
        System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsUsingHMACResponse> GetSubjectVisitClinicalDataRecordsUsingHMACAsync(DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsUsingHMACRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectVisitUnReadClinicalDataRecordsUsingHMAC" +
            "", ReplyAction="http://tempuri.org/IPIERService/GetSubjectVisitUnReadClinicalDataRecordsUsingHMAC" +
            "Response")]
        DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResponse GetSubjectVisitUnReadClinicalDataRecordsUsingHMAC(DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectVisitUnReadClinicalDataRecordsUsingHMAC" +
            "", ReplyAction="http://tempuri.org/IPIERService/GetSubjectVisitUnReadClinicalDataRecordsUsingHMAC" +
            "Response")]
        System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResponse> GetSubjectVisitUnReadClinicalDataRecordsUsingHMACAsync(DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectClinicalDataRecordsUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/GetSubjectClinicalDataRecordsUsingHMACResponse")]
        DebugTest.PIERService.GetSubjectClinicalDataRecordsUsingHMACResponse GetSubjectClinicalDataRecordsUsingHMAC(DebugTest.PIERService.GetSubjectClinicalDataRecordsUsingHMACRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/GetSubjectClinicalDataRecordsUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/GetSubjectClinicalDataRecordsUsingHMACResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectClinicalDataRecordsUsingHMACResponse> GetSubjectClinicalDataRecordsUsingHMACAsync(DebugTest.PIERService.GetSubjectClinicalDataRecordsUsingHMACRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/SetSubjectVisitAsReadUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/SetSubjectVisitAsReadUsingHMACResponse")]
        DebugTest.PIERService.SetSubjectVisitAsReadUsingHMACResponse SetSubjectVisitAsReadUsingHMAC(DebugTest.PIERService.SetSubjectVisitAsReadUsingHMACRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/SetSubjectVisitAsReadUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/SetSubjectVisitAsReadUsingHMACResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.SetSubjectVisitAsReadUsingHMACResponse> SetSubjectVisitAsReadUsingHMACAsync(DebugTest.PIERService.SetSubjectVisitAsReadUsingHMACRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/SetClinicalDataRecordsAsReadUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/SetClinicalDataRecordsAsReadUsingHMACResponse")]
        DebugTest.PIERService.SetClinicalDataRecordsAsReadUsingHMACResponse SetClinicalDataRecordsAsReadUsingHMAC(DebugTest.PIERService.SetClinicalDataRecordsAsReadUsingHMACRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/SetClinicalDataRecordsAsReadUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/SetClinicalDataRecordsAsReadUsingHMACResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.SetClinicalDataRecordsAsReadUsingHMACResponse> SetClinicalDataRecordsAsReadUsingHMACAsync(DebugTest.PIERService.SetClinicalDataRecordsAsReadUsingHMACRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/VerifyUserUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/VerifyUserUsingHMACResponse")]
        DebugTest.PIERService.VerifyUserUsingHMACResponse VerifyUserUsingHMAC(DebugTest.PIERService.VerifyUserUsingHMACRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIERService/VerifyUserUsingHMAC", ReplyAction="http://tempuri.org/IPIERService/VerifyUserUsingHMACResponse")]
        System.Threading.Tasks.Task<DebugTest.PIERService.VerifyUserUsingHMACResponse> VerifyUserUsingHMACAsync(DebugTest.PIERService.VerifyUserUsingHMACRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartSession", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string hostName;
        
        public StartSessionRequest() {
        }
        
        public StartSessionRequest(string userName, string userPassword, string hostName) {
            this.userName = userName;
            this.userPassword = userPassword;
            this.hostName = hostName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartSessionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string StartSessionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool mustChangePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool isLocked;
        
        public StartSessionResponse() {
        }
        
        public StartSessionResponse(string StartSessionResult, string error, bool mustChangePassword, bool isLocked) {
            this.StartSessionResult = StartSessionResult;
            this.error = error;
            this.mustChangePassword = mustChangePassword;
            this.isLocked = isLocked;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectRecordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sessionKey;
        
        public GetSubjectRecordsRequest() {
        }
        
        public GetSubjectRecordsRequest(string protocolCode, string sessionKey) {
            this.protocolCode = protocolCode;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetSubjectRecordsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public GetSubjectRecordsResponse() {
        }
        
        public GetSubjectRecordsResponse(System.Data.DataSet GetSubjectRecordsResult, string errStrRef) {
            this.GetSubjectRecordsResult = GetSubjectRecordsResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectClinicalDataRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectClinicalDataRecordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] subjects;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sessionKey;
        
        public GetSubjectClinicalDataRecordsRequest() {
        }
        
        public GetSubjectClinicalDataRecordsRequest(string protocolCode, string[] subjects, string sessionKey) {
            this.protocolCode = protocolCode;
            this.subjects = subjects;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectClinicalDataRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectClinicalDataRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetSubjectClinicalDataRecordsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public GetSubjectClinicalDataRecordsResponse() {
        }
        
        public GetSubjectClinicalDataRecordsResponse(System.Data.DataSet GetSubjectClinicalDataRecordsResult, string errStrRef) {
            this.GetSubjectClinicalDataRecordsResult = GetSubjectClinicalDataRecordsResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectVisitClinicalDataRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectVisitClinicalDataRecordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string visit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sessionKey;
        
        public GetSubjectVisitClinicalDataRecordsRequest() {
        }
        
        public GetSubjectVisitClinicalDataRecordsRequest(string protocolCode, string subject, string visit, string sessionKey) {
            this.protocolCode = protocolCode;
            this.subject = subject;
            this.visit = visit;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectVisitClinicalDataRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectVisitClinicalDataRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetSubjectVisitClinicalDataRecordsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public GetSubjectVisitClinicalDataRecordsResponse() {
        }
        
        public GetSubjectVisitClinicalDataRecordsResponse(System.Data.DataSet GetSubjectVisitClinicalDataRecordsResult, string errStrRef) {
            this.GetSubjectVisitClinicalDataRecordsResult = GetSubjectVisitClinicalDataRecordsResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectVisitUnReadClinicalDataRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectVisitUnReadClinicalDataRecordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string visit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sessionKey;
        
        public GetSubjectVisitUnReadClinicalDataRecordsRequest() {
        }
        
        public GetSubjectVisitUnReadClinicalDataRecordsRequest(string protocolCode, string subject, string visit, string sessionKey) {
            this.protocolCode = protocolCode;
            this.subject = subject;
            this.visit = visit;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectVisitUnReadClinicalDataRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectVisitUnReadClinicalDataRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetSubjectVisitUnReadClinicalDataRecordsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public GetSubjectVisitUnReadClinicalDataRecordsResponse() {
        }
        
        public GetSubjectVisitUnReadClinicalDataRecordsResponse(System.Data.DataSet GetSubjectVisitUnReadClinicalDataRecordsResult, string errStrRef) {
            this.GetSubjectVisitUnReadClinicalDataRecordsResult = GetSubjectVisitUnReadClinicalDataRecordsResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetSubjectVisitAsRead", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetSubjectVisitAsReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string visit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sessionKey;
        
        public SetSubjectVisitAsReadRequest() {
        }
        
        public SetSubjectVisitAsReadRequest(string protocolCode, string subject, string visit, string sessionKey) {
            this.protocolCode = protocolCode;
            this.subject = subject;
            this.visit = visit;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetSubjectVisitAsReadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetSubjectVisitAsReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetSubjectVisitAsReadResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public SetSubjectVisitAsReadResponse() {
        }
        
        public SetSubjectVisitAsReadResponse(bool SetSubjectVisitAsReadResult, string errStrRef) {
            this.SetSubjectVisitAsReadResult = SetSubjectVisitAsReadResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetClinicalDataRecordsAsRead", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetClinicalDataRecordsAsReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string templateName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.DataTable dt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sessionKey;
        
        public SetClinicalDataRecordsAsReadRequest() {
        }
        
        public SetClinicalDataRecordsAsReadRequest(string protocolCode, string templateName, System.Data.DataTable dt, string sessionKey) {
            this.protocolCode = protocolCode;
            this.templateName = templateName;
            this.dt = dt;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetClinicalDataRecordsAsReadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetClinicalDataRecordsAsReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetClinicalDataRecordsAsReadResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public SetClinicalDataRecordsAsReadResponse() {
        }
        
        public SetClinicalDataRecordsAsReadResponse(bool SetClinicalDataRecordsAsReadResult, string errStrRef) {
            this.SetClinicalDataRecordsAsReadResult = SetClinicalDataRecordsAsReadResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartSessionUsingHMAC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartSessionUsingHMACRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string timeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string hostName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string hmac;
        
        public StartSessionUsingHMACRequest() {
        }
        
        public StartSessionUsingHMACRequest(string userName, string timeStamp, string hostName, string hmac) {
            this.userName = userName;
            this.timeStamp = timeStamp;
            this.hostName = hostName;
            this.hmac = hmac;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartSessionUsingHMACResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartSessionUsingHMACResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string StartSessionUsingHMACResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool mustChangePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool isLocked;
        
        public StartSessionUsingHMACResponse() {
        }
        
        public StartSessionUsingHMACResponse(string StartSessionUsingHMACResult, string error, bool mustChangePassword, bool isLocked) {
            this.StartSessionUsingHMACResult = StartSessionUsingHMACResult;
            this.error = error;
            this.mustChangePassword = mustChangePassword;
            this.isLocked = isLocked;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestUserSessionKeyUsingHMAC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLatestUserSessionKeyUsingHMACRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string timeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string hmac;
        
        public GetLatestUserSessionKeyUsingHMACRequest() {
        }
        
        public GetLatestUserSessionKeyUsingHMACRequest(string userName, string timeStamp, string hmac) {
            this.userName = userName;
            this.timeStamp = timeStamp;
            this.hmac = hmac;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestUserSessionKeyUsingHMACResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLatestUserSessionKeyUsingHMACResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetLatestUserSessionKeyUsingHMACResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public GetLatestUserSessionKeyUsingHMACResponse() {
        }
        
        public GetLatestUserSessionKeyUsingHMACResponse(string GetLatestUserSessionKeyUsingHMACResult, string errStrRef) {
            this.GetLatestUserSessionKeyUsingHMACResult = GetLatestUserSessionKeyUsingHMACResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectRecordsUsingHMAC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectRecordsUsingHMACRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string timeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string hmac;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sessionKey;
        
        public GetSubjectRecordsUsingHMACRequest() {
        }
        
        public GetSubjectRecordsUsingHMACRequest(string userName, string timeStamp, string hmac, string protocolCode, string sessionKey) {
            this.userName = userName;
            this.timeStamp = timeStamp;
            this.hmac = hmac;
            this.protocolCode = protocolCode;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectRecordsUsingHMACResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectRecordsUsingHMACResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetSubjectRecordsUsingHMACResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public GetSubjectRecordsUsingHMACResponse() {
        }
        
        public GetSubjectRecordsUsingHMACResponse(System.Data.DataSet GetSubjectRecordsUsingHMACResult, string errStrRef) {
            this.GetSubjectRecordsUsingHMACResult = GetSubjectRecordsUsingHMACResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectVisitClinicalDataRecordsUsingHMAC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectVisitClinicalDataRecordsUsingHMACRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string timeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string hmac;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string visit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string sessionKey;
        
        public GetSubjectVisitClinicalDataRecordsUsingHMACRequest() {
        }
        
        public GetSubjectVisitClinicalDataRecordsUsingHMACRequest(string userName, string timeStamp, string hmac, string protocolCode, string subject, string visit, string sessionKey) {
            this.userName = userName;
            this.timeStamp = timeStamp;
            this.hmac = hmac;
            this.protocolCode = protocolCode;
            this.subject = subject;
            this.visit = visit;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectVisitClinicalDataRecordsUsingHMACResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectVisitClinicalDataRecordsUsingHMACResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetSubjectVisitClinicalDataRecordsUsingHMACResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public GetSubjectVisitClinicalDataRecordsUsingHMACResponse() {
        }
        
        public GetSubjectVisitClinicalDataRecordsUsingHMACResponse(System.Data.DataSet GetSubjectVisitClinicalDataRecordsUsingHMACResult, string errStrRef) {
            this.GetSubjectVisitClinicalDataRecordsUsingHMACResult = GetSubjectVisitClinicalDataRecordsUsingHMACResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectVisitUnReadClinicalDataRecordsUsingHMAC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectVisitUnReadClinicalDataRecordsUsingHMACRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string timeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string hmac;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string visit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string sessionKey;
        
        public GetSubjectVisitUnReadClinicalDataRecordsUsingHMACRequest() {
        }
        
        public GetSubjectVisitUnReadClinicalDataRecordsUsingHMACRequest(string userName, string timeStamp, string hmac, string protocolCode, string subject, string visit, string sessionKey) {
            this.userName = userName;
            this.timeStamp = timeStamp;
            this.hmac = hmac;
            this.protocolCode = protocolCode;
            this.subject = subject;
            this.visit = visit;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResponse() {
        }
        
        public GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResponse(System.Data.DataSet GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResult, string errStrRef) {
            this.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResult = GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectClinicalDataRecordsUsingHMAC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectClinicalDataRecordsUsingHMACRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string timeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string hmac;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string[] subjects;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string sessionKey;
        
        public GetSubjectClinicalDataRecordsUsingHMACRequest() {
        }
        
        public GetSubjectClinicalDataRecordsUsingHMACRequest(string userName, string timeStamp, string hmac, string protocolCode, string[] subjects, string sessionKey) {
            this.userName = userName;
            this.timeStamp = timeStamp;
            this.hmac = hmac;
            this.protocolCode = protocolCode;
            this.subjects = subjects;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubjectClinicalDataRecordsUsingHMACResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubjectClinicalDataRecordsUsingHMACResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetSubjectClinicalDataRecordsUsingHMACResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public GetSubjectClinicalDataRecordsUsingHMACResponse() {
        }
        
        public GetSubjectClinicalDataRecordsUsingHMACResponse(System.Data.DataSet GetSubjectClinicalDataRecordsUsingHMACResult, string errStrRef) {
            this.GetSubjectClinicalDataRecordsUsingHMACResult = GetSubjectClinicalDataRecordsUsingHMACResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetSubjectVisitAsReadUsingHMAC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetSubjectVisitAsReadUsingHMACRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string timeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string hmac;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string visit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string sessionKey;
        
        public SetSubjectVisitAsReadUsingHMACRequest() {
        }
        
        public SetSubjectVisitAsReadUsingHMACRequest(string userName, string timeStamp, string hmac, string protocolCode, string subject, string visit, string sessionKey) {
            this.userName = userName;
            this.timeStamp = timeStamp;
            this.hmac = hmac;
            this.protocolCode = protocolCode;
            this.subject = subject;
            this.visit = visit;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetSubjectVisitAsReadUsingHMACResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetSubjectVisitAsReadUsingHMACResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetSubjectVisitAsReadUsingHMACResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public SetSubjectVisitAsReadUsingHMACResponse() {
        }
        
        public SetSubjectVisitAsReadUsingHMACResponse(bool SetSubjectVisitAsReadUsingHMACResult, string errStrRef) {
            this.SetSubjectVisitAsReadUsingHMACResult = SetSubjectVisitAsReadUsingHMACResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetClinicalDataRecordsAsReadUsingHMAC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetClinicalDataRecordsAsReadUsingHMACRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string timeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string hmac;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string protocolCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string templateName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.Data.DataTable dt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string sessionKey;
        
        public SetClinicalDataRecordsAsReadUsingHMACRequest() {
        }
        
        public SetClinicalDataRecordsAsReadUsingHMACRequest(string userName, string timeStamp, string hmac, string protocolCode, string templateName, System.Data.DataTable dt, string sessionKey) {
            this.userName = userName;
            this.timeStamp = timeStamp;
            this.hmac = hmac;
            this.protocolCode = protocolCode;
            this.templateName = templateName;
            this.dt = dt;
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetClinicalDataRecordsAsReadUsingHMACResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetClinicalDataRecordsAsReadUsingHMACResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetClinicalDataRecordsAsReadUsingHMACResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public SetClinicalDataRecordsAsReadUsingHMACResponse() {
        }
        
        public SetClinicalDataRecordsAsReadUsingHMACResponse(bool SetClinicalDataRecordsAsReadUsingHMACResult, string errStrRef) {
            this.SetClinicalDataRecordsAsReadUsingHMACResult = SetClinicalDataRecordsAsReadUsingHMACResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyUserUsingHMAC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyUserUsingHMACRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string timeStamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string hmac;
        
        public VerifyUserUsingHMACRequest() {
        }
        
        public VerifyUserUsingHMACRequest(string userName, string timeStamp, string hmac) {
            this.userName = userName;
            this.timeStamp = timeStamp;
            this.hmac = hmac;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyUserUsingHMACResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyUserUsingHMACResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool VerifyUserUsingHMACResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errStrRef;
        
        public VerifyUserUsingHMACResponse() {
        }
        
        public VerifyUserUsingHMACResponse(bool VerifyUserUsingHMACResult, string errStrRef) {
            this.VerifyUserUsingHMACResult = VerifyUserUsingHMACResult;
            this.errStrRef = errStrRef;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPIERServiceChannel : DebugTest.PIERService.IPIERService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PIERServiceClient : System.ServiceModel.ClientBase<DebugTest.PIERService.IPIERService>, DebugTest.PIERService.IPIERService {
        
        public PIERServiceClient() {
        }
        
        public PIERServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PIERServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIERServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIERServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.StartSessionResponse DebugTest.PIERService.IPIERService.StartSession(DebugTest.PIERService.StartSessionRequest request) {
            return base.Channel.StartSession(request);
        }
        
        public string StartSession(string userName, string userPassword, string hostName, out string error, out bool mustChangePassword, out bool isLocked) {
            DebugTest.PIERService.StartSessionRequest inValue = new DebugTest.PIERService.StartSessionRequest();
            inValue.userName = userName;
            inValue.userPassword = userPassword;
            inValue.hostName = hostName;
            DebugTest.PIERService.StartSessionResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).StartSession(inValue);
            error = retVal.error;
            mustChangePassword = retVal.mustChangePassword;
            isLocked = retVal.isLocked;
            return retVal.StartSessionResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.StartSessionResponse> StartSessionAsync(DebugTest.PIERService.StartSessionRequest request) {
            return base.Channel.StartSessionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.GetSubjectRecordsResponse DebugTest.PIERService.IPIERService.GetSubjectRecords(DebugTest.PIERService.GetSubjectRecordsRequest request) {
            return base.Channel.GetSubjectRecords(request);
        }
        
        public System.Data.DataSet GetSubjectRecords(string protocolCode, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.GetSubjectRecordsRequest inValue = new DebugTest.PIERService.GetSubjectRecordsRequest();
            inValue.protocolCode = protocolCode;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.GetSubjectRecordsResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).GetSubjectRecords(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.GetSubjectRecordsResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectRecordsResponse> GetSubjectRecordsAsync(DebugTest.PIERService.GetSubjectRecordsRequest request) {
            return base.Channel.GetSubjectRecordsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.GetSubjectClinicalDataRecordsResponse DebugTest.PIERService.IPIERService.GetSubjectClinicalDataRecords(DebugTest.PIERService.GetSubjectClinicalDataRecordsRequest request) {
            return base.Channel.GetSubjectClinicalDataRecords(request);
        }
        
        public System.Data.DataSet GetSubjectClinicalDataRecords(string protocolCode, string[] subjects, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.GetSubjectClinicalDataRecordsRequest inValue = new DebugTest.PIERService.GetSubjectClinicalDataRecordsRequest();
            inValue.protocolCode = protocolCode;
            inValue.subjects = subjects;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.GetSubjectClinicalDataRecordsResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).GetSubjectClinicalDataRecords(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.GetSubjectClinicalDataRecordsResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectClinicalDataRecordsResponse> GetSubjectClinicalDataRecordsAsync(DebugTest.PIERService.GetSubjectClinicalDataRecordsRequest request) {
            return base.Channel.GetSubjectClinicalDataRecordsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsResponse DebugTest.PIERService.IPIERService.GetSubjectVisitClinicalDataRecords(DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsRequest request) {
            return base.Channel.GetSubjectVisitClinicalDataRecords(request);
        }
        
        public System.Data.DataSet GetSubjectVisitClinicalDataRecords(string protocolCode, string subject, string visit, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsRequest inValue = new DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsRequest();
            inValue.protocolCode = protocolCode;
            inValue.subject = subject;
            inValue.visit = visit;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).GetSubjectVisitClinicalDataRecords(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.GetSubjectVisitClinicalDataRecordsResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsResponse> GetSubjectVisitClinicalDataRecordsAsync(DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsRequest request) {
            return base.Channel.GetSubjectVisitClinicalDataRecordsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsResponse DebugTest.PIERService.IPIERService.GetSubjectVisitUnReadClinicalDataRecords(DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsRequest request) {
            return base.Channel.GetSubjectVisitUnReadClinicalDataRecords(request);
        }
        
        public System.Data.DataSet GetSubjectVisitUnReadClinicalDataRecords(string protocolCode, string subject, string visit, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsRequest inValue = new DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsRequest();
            inValue.protocolCode = protocolCode;
            inValue.subject = subject;
            inValue.visit = visit;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).GetSubjectVisitUnReadClinicalDataRecords(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.GetSubjectVisitUnReadClinicalDataRecordsResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsResponse> GetSubjectVisitUnReadClinicalDataRecordsAsync(DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsRequest request) {
            return base.Channel.GetSubjectVisitUnReadClinicalDataRecordsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.SetSubjectVisitAsReadResponse DebugTest.PIERService.IPIERService.SetSubjectVisitAsRead(DebugTest.PIERService.SetSubjectVisitAsReadRequest request) {
            return base.Channel.SetSubjectVisitAsRead(request);
        }
        
        public bool SetSubjectVisitAsRead(string protocolCode, string subject, string visit, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.SetSubjectVisitAsReadRequest inValue = new DebugTest.PIERService.SetSubjectVisitAsReadRequest();
            inValue.protocolCode = protocolCode;
            inValue.subject = subject;
            inValue.visit = visit;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.SetSubjectVisitAsReadResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).SetSubjectVisitAsRead(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.SetSubjectVisitAsReadResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.SetSubjectVisitAsReadResponse> SetSubjectVisitAsReadAsync(DebugTest.PIERService.SetSubjectVisitAsReadRequest request) {
            return base.Channel.SetSubjectVisitAsReadAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.SetClinicalDataRecordsAsReadResponse DebugTest.PIERService.IPIERService.SetClinicalDataRecordsAsRead(DebugTest.PIERService.SetClinicalDataRecordsAsReadRequest request) {
            return base.Channel.SetClinicalDataRecordsAsRead(request);
        }
        
        public bool SetClinicalDataRecordsAsRead(string protocolCode, string templateName, System.Data.DataTable dt, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.SetClinicalDataRecordsAsReadRequest inValue = new DebugTest.PIERService.SetClinicalDataRecordsAsReadRequest();
            inValue.protocolCode = protocolCode;
            inValue.templateName = templateName;
            inValue.dt = dt;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.SetClinicalDataRecordsAsReadResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).SetClinicalDataRecordsAsRead(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.SetClinicalDataRecordsAsReadResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.SetClinicalDataRecordsAsReadResponse> SetClinicalDataRecordsAsReadAsync(DebugTest.PIERService.SetClinicalDataRecordsAsReadRequest request) {
            return base.Channel.SetClinicalDataRecordsAsReadAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.StartSessionUsingHMACResponse DebugTest.PIERService.IPIERService.StartSessionUsingHMAC(DebugTest.PIERService.StartSessionUsingHMACRequest request) {
            return base.Channel.StartSessionUsingHMAC(request);
        }
        
        public string StartSessionUsingHMAC(string userName, string timeStamp, string hostName, string hmac, out string error, out bool mustChangePassword, out bool isLocked) {
            DebugTest.PIERService.StartSessionUsingHMACRequest inValue = new DebugTest.PIERService.StartSessionUsingHMACRequest();
            inValue.userName = userName;
            inValue.timeStamp = timeStamp;
            inValue.hostName = hostName;
            inValue.hmac = hmac;
            DebugTest.PIERService.StartSessionUsingHMACResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).StartSessionUsingHMAC(inValue);
            error = retVal.error;
            mustChangePassword = retVal.mustChangePassword;
            isLocked = retVal.isLocked;
            return retVal.StartSessionUsingHMACResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.StartSessionUsingHMACResponse> StartSessionUsingHMACAsync(DebugTest.PIERService.StartSessionUsingHMACRequest request) {
            return base.Channel.StartSessionUsingHMACAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.GetLatestUserSessionKeyUsingHMACResponse DebugTest.PIERService.IPIERService.GetLatestUserSessionKeyUsingHMAC(DebugTest.PIERService.GetLatestUserSessionKeyUsingHMACRequest request) {
            return base.Channel.GetLatestUserSessionKeyUsingHMAC(request);
        }
        
        public string GetLatestUserSessionKeyUsingHMAC(string userName, string timeStamp, string hmac, out string errStrRef) {
            DebugTest.PIERService.GetLatestUserSessionKeyUsingHMACRequest inValue = new DebugTest.PIERService.GetLatestUserSessionKeyUsingHMACRequest();
            inValue.userName = userName;
            inValue.timeStamp = timeStamp;
            inValue.hmac = hmac;
            DebugTest.PIERService.GetLatestUserSessionKeyUsingHMACResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).GetLatestUserSessionKeyUsingHMAC(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.GetLatestUserSessionKeyUsingHMACResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.GetLatestUserSessionKeyUsingHMACResponse> GetLatestUserSessionKeyUsingHMACAsync(DebugTest.PIERService.GetLatestUserSessionKeyUsingHMACRequest request) {
            return base.Channel.GetLatestUserSessionKeyUsingHMACAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.GetSubjectRecordsUsingHMACResponse DebugTest.PIERService.IPIERService.GetSubjectRecordsUsingHMAC(DebugTest.PIERService.GetSubjectRecordsUsingHMACRequest request) {
            return base.Channel.GetSubjectRecordsUsingHMAC(request);
        }
        
        public System.Data.DataSet GetSubjectRecordsUsingHMAC(string userName, string timeStamp, string hmac, string protocolCode, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.GetSubjectRecordsUsingHMACRequest inValue = new DebugTest.PIERService.GetSubjectRecordsUsingHMACRequest();
            inValue.userName = userName;
            inValue.timeStamp = timeStamp;
            inValue.hmac = hmac;
            inValue.protocolCode = protocolCode;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.GetSubjectRecordsUsingHMACResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).GetSubjectRecordsUsingHMAC(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.GetSubjectRecordsUsingHMACResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectRecordsUsingHMACResponse> GetSubjectRecordsUsingHMACAsync(DebugTest.PIERService.GetSubjectRecordsUsingHMACRequest request) {
            return base.Channel.GetSubjectRecordsUsingHMACAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsUsingHMACResponse DebugTest.PIERService.IPIERService.GetSubjectVisitClinicalDataRecordsUsingHMAC(DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsUsingHMACRequest request) {
            return base.Channel.GetSubjectVisitClinicalDataRecordsUsingHMAC(request);
        }
        
        public System.Data.DataSet GetSubjectVisitClinicalDataRecordsUsingHMAC(string userName, string timeStamp, string hmac, string protocolCode, string subject, string visit, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsUsingHMACRequest inValue = new DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsUsingHMACRequest();
            inValue.userName = userName;
            inValue.timeStamp = timeStamp;
            inValue.hmac = hmac;
            inValue.protocolCode = protocolCode;
            inValue.subject = subject;
            inValue.visit = visit;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsUsingHMACResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).GetSubjectVisitClinicalDataRecordsUsingHMAC(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.GetSubjectVisitClinicalDataRecordsUsingHMACResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsUsingHMACResponse> GetSubjectVisitClinicalDataRecordsUsingHMACAsync(DebugTest.PIERService.GetSubjectVisitClinicalDataRecordsUsingHMACRequest request) {
            return base.Channel.GetSubjectVisitClinicalDataRecordsUsingHMACAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResponse DebugTest.PIERService.IPIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMAC(DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACRequest request) {
            return base.Channel.GetSubjectVisitUnReadClinicalDataRecordsUsingHMAC(request);
        }
        
        public System.Data.DataSet GetSubjectVisitUnReadClinicalDataRecordsUsingHMAC(string userName, string timeStamp, string hmac, string protocolCode, string subject, string visit, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACRequest inValue = new DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACRequest();
            inValue.userName = userName;
            inValue.timeStamp = timeStamp;
            inValue.hmac = hmac;
            inValue.protocolCode = protocolCode;
            inValue.subject = subject;
            inValue.visit = visit;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).GetSubjectVisitUnReadClinicalDataRecordsUsingHMAC(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACResponse> GetSubjectVisitUnReadClinicalDataRecordsUsingHMACAsync(DebugTest.PIERService.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACRequest request) {
            return base.Channel.GetSubjectVisitUnReadClinicalDataRecordsUsingHMACAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.GetSubjectClinicalDataRecordsUsingHMACResponse DebugTest.PIERService.IPIERService.GetSubjectClinicalDataRecordsUsingHMAC(DebugTest.PIERService.GetSubjectClinicalDataRecordsUsingHMACRequest request) {
            return base.Channel.GetSubjectClinicalDataRecordsUsingHMAC(request);
        }
        
        public System.Data.DataSet GetSubjectClinicalDataRecordsUsingHMAC(string userName, string timeStamp, string hmac, string protocolCode, string[] subjects, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.GetSubjectClinicalDataRecordsUsingHMACRequest inValue = new DebugTest.PIERService.GetSubjectClinicalDataRecordsUsingHMACRequest();
            inValue.userName = userName;
            inValue.timeStamp = timeStamp;
            inValue.hmac = hmac;
            inValue.protocolCode = protocolCode;
            inValue.subjects = subjects;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.GetSubjectClinicalDataRecordsUsingHMACResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).GetSubjectClinicalDataRecordsUsingHMAC(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.GetSubjectClinicalDataRecordsUsingHMACResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.GetSubjectClinicalDataRecordsUsingHMACResponse> GetSubjectClinicalDataRecordsUsingHMACAsync(DebugTest.PIERService.GetSubjectClinicalDataRecordsUsingHMACRequest request) {
            return base.Channel.GetSubjectClinicalDataRecordsUsingHMACAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.SetSubjectVisitAsReadUsingHMACResponse DebugTest.PIERService.IPIERService.SetSubjectVisitAsReadUsingHMAC(DebugTest.PIERService.SetSubjectVisitAsReadUsingHMACRequest request) {
            return base.Channel.SetSubjectVisitAsReadUsingHMAC(request);
        }
        
        public bool SetSubjectVisitAsReadUsingHMAC(string userName, string timeStamp, string hmac, string protocolCode, string subject, string visit, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.SetSubjectVisitAsReadUsingHMACRequest inValue = new DebugTest.PIERService.SetSubjectVisitAsReadUsingHMACRequest();
            inValue.userName = userName;
            inValue.timeStamp = timeStamp;
            inValue.hmac = hmac;
            inValue.protocolCode = protocolCode;
            inValue.subject = subject;
            inValue.visit = visit;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.SetSubjectVisitAsReadUsingHMACResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).SetSubjectVisitAsReadUsingHMAC(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.SetSubjectVisitAsReadUsingHMACResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.SetSubjectVisitAsReadUsingHMACResponse> SetSubjectVisitAsReadUsingHMACAsync(DebugTest.PIERService.SetSubjectVisitAsReadUsingHMACRequest request) {
            return base.Channel.SetSubjectVisitAsReadUsingHMACAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.SetClinicalDataRecordsAsReadUsingHMACResponse DebugTest.PIERService.IPIERService.SetClinicalDataRecordsAsReadUsingHMAC(DebugTest.PIERService.SetClinicalDataRecordsAsReadUsingHMACRequest request) {
            return base.Channel.SetClinicalDataRecordsAsReadUsingHMAC(request);
        }
        
        public bool SetClinicalDataRecordsAsReadUsingHMAC(string userName, string timeStamp, string hmac, string protocolCode, string templateName, System.Data.DataTable dt, string sessionKey, out string errStrRef) {
            DebugTest.PIERService.SetClinicalDataRecordsAsReadUsingHMACRequest inValue = new DebugTest.PIERService.SetClinicalDataRecordsAsReadUsingHMACRequest();
            inValue.userName = userName;
            inValue.timeStamp = timeStamp;
            inValue.hmac = hmac;
            inValue.protocolCode = protocolCode;
            inValue.templateName = templateName;
            inValue.dt = dt;
            inValue.sessionKey = sessionKey;
            DebugTest.PIERService.SetClinicalDataRecordsAsReadUsingHMACResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).SetClinicalDataRecordsAsReadUsingHMAC(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.SetClinicalDataRecordsAsReadUsingHMACResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.SetClinicalDataRecordsAsReadUsingHMACResponse> SetClinicalDataRecordsAsReadUsingHMACAsync(DebugTest.PIERService.SetClinicalDataRecordsAsReadUsingHMACRequest request) {
            return base.Channel.SetClinicalDataRecordsAsReadUsingHMACAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebugTest.PIERService.VerifyUserUsingHMACResponse DebugTest.PIERService.IPIERService.VerifyUserUsingHMAC(DebugTest.PIERService.VerifyUserUsingHMACRequest request) {
            return base.Channel.VerifyUserUsingHMAC(request);
        }
        
        public bool VerifyUserUsingHMAC(string userName, string timeStamp, string hmac, out string errStrRef) {
            DebugTest.PIERService.VerifyUserUsingHMACRequest inValue = new DebugTest.PIERService.VerifyUserUsingHMACRequest();
            inValue.userName = userName;
            inValue.timeStamp = timeStamp;
            inValue.hmac = hmac;
            DebugTest.PIERService.VerifyUserUsingHMACResponse retVal = ((DebugTest.PIERService.IPIERService)(this)).VerifyUserUsingHMAC(inValue);
            errStrRef = retVal.errStrRef;
            return retVal.VerifyUserUsingHMACResult;
        }
        
        public System.Threading.Tasks.Task<DebugTest.PIERService.VerifyUserUsingHMACResponse> VerifyUserUsingHMACAsync(DebugTest.PIERService.VerifyUserUsingHMACRequest request) {
            return base.Channel.VerifyUserUsingHMACAsync(request);
        }
    }
}
